// node logo-mask.cjs <logo.png> <out.mjs> <dotsWide>
// Samples the Shape logo (public/SHAPE-logo-teal-white.png: a teal ▸, a white ◂ chevron and the
// SHAPE wordmark on transparent) onto an LED dot grid: each dot takes the area coverage of the
// logo pixels under it, split into white and teal. Writes src/shapeLogoMask.mjs, which club.mjs
// draws on the stage screen. Pure Node (zlib); no image libraries.
const fs = require('fs'), zlib = require('zlib');
const [,, src, out, wideArg] = process.argv;
const buf = fs.readFileSync(src);
let o = 8, W = 0, H = 0, depth = 0, type = 0; const idat = [];
while (o < buf.length) {
  const len = buf.readUInt32BE(o), kind = buf.toString('ascii', o + 4, o + 8), data = buf.subarray(o + 8, o + 8 + len);
  if (kind === 'IHDR') { W = data.readUInt32BE(0); H = data.readUInt32BE(4); depth = data[8]; type = data[9]; if (data[12]) throw new Error('interlaced PNG'); }
  else if (kind === 'IDAT') idat.push(data);
  o += 12 + len;
}
if (depth !== 8 || type !== 6) throw new Error(`need 8-bit RGBA, got depth ${depth} type ${type}`);
const raw = zlib.inflateSync(Buffer.concat(idat)), bpp = 4, stride = W * bpp, px = new Uint8Array(H * stride);
for (let y = 0; y < H; y++) {
  const f = raw[y * (stride + 1)], row = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1));
  for (let x = 0; x < stride; x++) {
    const a = x >= bpp ? px[y * stride + x - bpp] : 0, b = y ? px[(y - 1) * stride + x] : 0, c = x >= bpp && y ? px[(y - 1) * stride + x - bpp] : 0;
    let v = row[x];
    if (f === 1) v += a; else if (f === 2) v += b; else if (f === 3) v += (a + b) >> 1;
    else if (f === 4) { const p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c); v += pa <= pb && pa <= pc ? a : pb <= pc ? b : c; }
    px[y * stride + x] = v & 255;
  }
}
// the logo's bounds (alpha > 20)
let x0 = W, y0 = H, x1 = 0, y1 = 0;
for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) if (px[(y * W + x) * 4 + 3] > 20) { if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; }
const bw = x1 - x0 + 1, bh = y1 - y0 + 1;
const cols = +wideArg || 168, cell = bw / cols, rows = Math.ceil(bh / cell);
const white = new Uint8Array(cols * rows), teal = new Uint8Array(cols * rows);
for (let r = 0; r < rows; r++) for (let q = 0; q < cols; q++) {
  let sw = 0, st = 0, n = 0;
  const ya = Math.floor(y0 + r * cell), yb = Math.min(H, Math.floor(y0 + (r + 1) * cell)), xa = Math.floor(x0 + q * cell), xb = Math.min(W, Math.floor(x0 + (q + 1) * cell));
  for (let y = ya; y < yb; y++) for (let x = xa; x < xb; x++) {
    const i = (y * W + x) * 4, al = px[i + 3] / 255;
    // teal where red is well under green and blue; white elsewhere
    const isTeal = px[i] < 150 && px[i + 1] > 140 && px[i + 2] > 140;
    if (isTeal) st += al; else sw += al;
    n++;
  }
  white[r * cols + q] = Math.round(15 * sw / Math.max(n, 1));
  teal[r * cols + q] = Math.round(15 * st / Math.max(n, 1));
}
const hex = (a) => Array.from(a, (v) => v.toString(16)).join('');
fs.writeFileSync(out, `// shapeLogoMask.mjs — GENERATED by logo-mask.cjs from public/SHAPE-logo-teal-white.png; do not edit.
// The Shape logo on an LED dot grid: ${cols} × ${rows} dots, rows top to bottom, one hex digit
// (0–15, area coverage) per dot for the white parts (the ◂ chevron and the SHAPE wordmark) and the
// teal ▸.
export const SHAPE_LOGO_MASK = {
  cols: ${cols},
  rows: ${rows},
  white: '${hex(white)}',
  teal: '${hex(teal)}',
};
`);
console.log(JSON.stringify({ png: [W, H], bounds: [x0, y0, bw, bh], cols, rows, lit: { white: white.filter((v) => v > 7).length, teal: teal.filter((v) => v > 7).length } }));
