// node screen-mask.mjs [preview.png]
// Writes public/newdesign/booth/clubShapeMask.mjs: the stage screen's artwork (the Shape mark over CLUB SHAPE, built by
// src/screenArt.mjs from the wordmark's strokes in src/wordmarkGlyphs.mjs) as per-dot coverage, one
// hex digit per dot for the white parts and the teal ▸. With a path, also writes a preview PNG of the
// dots. Re-run it after changing the glyphs, the layout or the dot grid; the test fails if the
// committed file is stale.
import { writeFileSync } from 'node:fs';
import { buildScreenArt, hex, ART } from './src/screenArt.mjs';
import { encodePng } from './src/pngRgba.mjs';

const m = buildScreenArt();
writeFileSync(new URL('../../public/newdesign/booth/clubShapeMask.mjs', import.meta.url), `// clubShapeMask.mjs — GENERATED by prototypes/nora-booth/screen-mask.mjs from prototypes/nora-booth/src/screenArt.mjs; do not edit.
// The stage screen's artwork on its LED dots: the Shape mark over ${ART.word}, ${m.cols} × ${m.rows} dots,
// rows top to bottom, one hex digit (0–15, area coverage) per dot for the white parts (the ◂ and the
// letters) and the teal ▸. Cap height ${m.capDots.toFixed(2)} dots; the mark ${m.markDots.toFixed(2)} dots tall.
export const CLUB_SHAPE_MASK = {
  cols: ${m.cols},
  rows: ${m.rows},
  white: '${hex(m.white)}',
  teal: '${hex(m.teal)}',
};
`);
const lit = (a) => a.filter((v) => v > 7).length;
console.log(JSON.stringify({ cols: m.cols, rows: m.rows, capDots: +m.capDots.toFixed(2), markDots: +m.markDots.toFixed(2), lit: { white: lit(m.white), teal: lit(m.teal) } }));
const out = process.argv[2];
if (out) {
  const P = 8, W = m.cols * P, H = m.rows * P, img = new Uint8Array(W * H * 4);
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    const q = (x / P) | 0, r = (y / P) | 0, i = r * m.cols + q, dx = (x % P) - P / 2 + 0.5, dy = (y % P) - P / 2 + 0.5;
    const on = Math.hypot(dx, dy) < P * 0.38, wv = m.white[i] / 15, tv = m.teal[i] / 15, o = (y * W + x) * 4;
    const f = on ? 1 : 0;
    const c = (b, w, t) => Math.min(255, Math.round(b + f * (w * wv + t * tv)));
    img[o] = c(8, 225, 52); img[o + 1] = c(12, 230, 214); img[o + 2] = c(16, 238, 197); img[o + 3] = 255;
  }
  encodePng(out, W, H, img);
}
