import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import React, {act} from 'react';
import {loadBroadsheet} from './helpers/broadsheet-mount.mjs';

const dom=new JSDOM('<!doctype html><div id="root"></div>',{url:'https://shape.test/m/'});
globalThis.document=dom.window.document;
globalThis.HTMLElement=dom.window.HTMLElement;
globalThis.HTMLInputElement=dom.window.HTMLInputElement;
globalThis.CustomEvent=dom.window.CustomEvent;
globalThis.addEventListener=dom.window.addEventListener.bind(dom.window);
globalThis.removeEventListener=dom.window.removeEventListener.bind(dom.window);
globalThis.dispatchEvent=dom.window.dispatchEvent.bind(dom.window);
globalThis.localStorage=dom.window.localStorage;
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
globalThis.useStateBSC=React.useState;
globalThis.requestAnimationFrame=fn=>setTimeout(fn,0);
globalThis.cancelAnimationFrame=clearTimeout;
globalThis.matchMedia=()=>({matches:true,addEventListener(){},removeEventListener(){}});
globalThis.ShapeAuth={getCachedState:()=>({user:{id:'client-a'}})};
globalThis.ShapeLiveProgress={clear(){},push(){}};
globalThis.shapeDb={getUserGoals:async()=>null};
const catalog=JSON.parse(readFileSync(new URL('../mobile-app/src/i18n/catalogs/en/session.json',import.meta.url),'utf8'));
globalThis.ShapeI18n={t:(key,opts={})=>String(catalog[key.replace('session:','')]||opts.defaultValue||key).replace(/\{(\w+)(?:,[^}]+)?\}/g,(match,name)=>opts[name]??match)};
const {BSSession}=await loadBroadsheet('BSSession',React);
const {createRoot}=await import('react-dom/client');
const rootElement=document.getElementById('root');
const moves=[{m:'Squat',sets:2,reps:'8',l:'60 kg',restSeconds:90,rpe:'8',cue:'Brace',video:'https://example.com/demo.mp4',tempo:'3010'}, {m:'Row',sets:1,reps:'10 each',l:'25 kg',restSeconds:60}];
let root;
const buttons=()=>[...rootElement.querySelectorAll('button')];
const button=label=>buttons().find(b=>b.getAttribute('aria-label')===label||b.textContent.trim()===label);
const click=async label=>{const b=button(label);assert.ok(!!b,'button: '+label);await act(async()=>b.click());};
const input=(name,section)=>[...(section||rootElement).querySelectorAll('input')].find(e=>e.getAttribute('aria-label')===name);
const type=async(el,value)=>{assert.ok(!!el);await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new dom.window.Event('input',{bubbles:true}));});};
const draft=()=>JSON.parse(localStorage.getItem('shapeClientWorkoutDrafts:client-a'))[0];
const mount=async props=>{root=createRoot(rootElement);await act(async()=>root.render(React.createElement(BSSession,{moves,onBack(){},...props})));};
const unmount=async()=>{if(root)await act(async()=>root.unmount());root=null;};

test('mounted views share typed values, logs, trainer rest and a durable client preference',async t=>{
  t.after(unmount);localStorage.clear();await mount();
  assert.match(rootElement.textContent,/Choose your workout view/);
  await click('Focus');assert.equal(localStorage.getItem('shapeClientWorkoutView:client-a'),'focus');
  await type(input('Set 1 Load'),'62.5 kg');
  await type(input('Set 1 RPE'),'7');
  await click('Log set 1 · 8 reps');
  const first=draft();assert.equal(first.setLogs[0].actualLoad,62.5);assert.equal(Number(first.setLogs[0].rpe),7);assert.equal(first.restTotal,90);
  await click('Change view');await click('Workout log');
  assert.equal(draft().restEnd,first.restEnd,'switch must retain the absolute rest deadline');
  const rowSection=document.getElementById('bs-log-move-1').closest('section');
  assert.equal(input('Set 1 Reps',rowSection).value,'10 each');
  await type(input('Set 1 Load',rowSection),'27.5 kg');
  await act(async()=>rowSection.querySelector('button[aria-label="Mark set 1 done"]').click());
  assert.equal(draft().setLogs.find(s=>s.moveIndex===1).actualLoad,27.5,'logging another exercise uses that row');
  assert.equal(draft().setLogs.find(s=>s.moveIndex===1).enteredReps,'10 each');
  await click('Change view');await click('Guided coach');
  const kept=draft();assert.equal(kept.setLogs.length,2);assert.equal(kept.view,'guided');
  await unmount();await mount({draft:kept});
  assert.doesNotMatch(rootElement.textContent,/Choose your workout view/);
  assert.match(rootElement.textContent,/Guided coach/);
  assert.equal(draft().setLogs.length,2);
  await click('Skip rest →');
  assert.ok(!!button('Ready for this set'));
  await click('Ready for this set');
  assert.match(rootElement.textContent,/02 · Perform & log/);
  assert.equal(draft().setLogs.length,2,'prepare does not log or invent timing');
});

test('mounted HR capture survives pause/recovery, clears on disconnect and freezes the private save payload',async t=>{
  t.after(unmount);localStorage.clear();const saved=[];
  globalThis.ShapeWorkoutLogs={saveSessionLog:async value=>{saved.push(value);return {workoutSession:{stored:'supabase'}}}};
  t.mock.timers.enable({apis:['Date','setInterval'],now:1700000000000});
  await mount();await click('Focus');
  await act(async()=>{dispatchEvent(new CustomEvent('shape:hrm',{detail:{bpm:120,connected:true}}));t.mock.timers.tick(1000);});
  assert.match(rootElement.textContent,/120 bpm/);
  await act(async()=>{dispatchEvent(new CustomEvent('shape:hrm',{detail:{bpm:140,connected:true}}));t.mock.timers.tick(1000);});
  await act(async()=>dispatchEvent(new CustomEvent('shape:hrm',{detail:{bpm:null,connected:false}})));
  assert.doesNotMatch(rootElement.textContent,/140 bpm/);assert.match(rootElement.textContent,/Signal lost/);
  await act(async()=>t.mock.timers.tick(1000));
  const kept=draft();assert.equal(kept.hrSamples.length,2);
  await unmount();await mount({draft:kept});
  await act(async()=>{dispatchEvent(new CustomEvent('shape:hrm',{detail:{bpm:130,connected:true}}));t.mock.timers.tick(1000);});
  await click('End workout early');
  await act(async()=>dispatchEvent(new CustomEvent('shape:hrm',{detail:{bpm:180,connected:true}})));
  await click('Save & finish ✓');
  assert.equal(saved.length,1);assert.equal(saved[0].hr.max,140);assert.equal(saved[0].hr.samples,3);
  assert.equal(saved[0].sensorSamples.length,3);assert.equal(saved[0].privacy,'private');
  assert.equal(localStorage.getItem('shapeClientWorkoutDrafts:client-a'),'[]');
});

test('a timed set keeps its start through view changes and cannot be replaced from another log row', async t => {
  t.after(unmount); localStorage.clear();
  t.mock.timers.enable({ apis: ['Date', 'setInterval'], now: 1700000000000 });
  await mount(); await click('Focus');
  await act(async () => rootElement.querySelector('summary').click());
  await click('Timed sets'); await click('Start set 1');
  const running = draft(); assert.equal(running.activeSetKey, '0-0');
  await act(async () => t.mock.timers.tick(5000));
  await click('Change view'); await click('Workout log');
  assert.equal(draft().setStartedAt, running.setStartedAt);
  const other = document.getElementById('bs-log-move-1').closest('section');
  await act(async () => other.querySelector('button[aria-label="Start set 1"]').click());
  assert.equal(draft().activeSetKey, '0-0'); assert.equal(draft().setStartedAt, running.setStartedAt);
  await click('Change view'); await click('Guided coach');
  assert.equal(draft().setStartedAt, running.setStartedAt);
  await click('Log set 1 · 8 reps');
  assert.equal(draft().setLogs[0].setDurationSeconds, 5);
});

test('a fresh HR event displays immediately between clock ticks, then expires without another event', async t => {
  t.after(unmount); localStorage.clear();
  t.mock.timers.enable({ apis: ['Date', 'setInterval'], now: 1700000000000 });
  await mount(); await click('Focus');
  await act(async () => { t.mock.timers.tick(450); dispatchEvent(new CustomEvent('shape:hrm', { detail: { bpm: 125, t: Date.now(), connected: true } })); });
  assert.match(rootElement.textContent, /125 bpm/);
  await act(async () => t.mock.timers.tick(16000));
  assert.doesNotMatch(rootElement.textContent, /125 bpm/);
  assert.match(rootElement.textContent, /waiting for a fresh reading/);
});
