-- The exercise library as data (2026-10-07, owner-approved coach-tools plan, "Build faster":
-- "The library is 75 moves hard-coded in a file, and search shows 12 at most. Move it into
-- the database with muscles, equipment and demo videos.").
--
-- Read by GET /api/exercises (src/app/api/exercises/route.ts), which ranks with the SAME
-- function the builder's type-ahead will use (DashBuilder.searchLibrary in
-- public/newdesign/dashBuilderCore.js), so the server and the picker cannot disagree about
-- what a query means. Until this runs the route serves the 75 built-in moves instead, so
-- nothing breaks in the meantime.
--
-- ===== WHAT IS IN IT =====
-- The 75 moves the builder already ships, with the SAME name, muscle and equipment, then a
-- broader set of common strength, power, conditioning and mobility moves. No brand names.
-- tests/exercise-library.test.mjs reads the VALUES below and holds them to the code: every
-- built-in move present and identical, the 75's aliases and category equal to
-- DashBuilder.LIBRARY_ALIASES / exerciseCategory, every id the slug of its name, no name or
-- alias claimed by two moves, and every category one the check below allows.
--
-- ===== THE ID IS THE SLUG OF THE NAME =====
-- 'back-squat', 'worlds-greatest-stretch'. Deterministic, so this file lands on the same
-- ids on any database (a branch DB included) and a later change can refer to a move by id.
--
-- ===== AN ALIAS NAMES THE SAME MOVEMENT, NEVER A FAMILY =====
-- Pasted text resolves a line that IS an alias to its move (DashBuilder.parseWorkoutText),
-- so an alias like "Row" on the rower would rename a strength coach's "Row 3x10" to an erg.
-- Abbreviations (RDL, OHP), spellings (Pullup) and the powerlifting conventions (Squat,
-- Bench) qualify; a word that names several moves does not.
--
-- ===== RE-RUNNING =====
-- Idempotent. The seed owns name, muscle, equipment, category and aliases, so a re-run
-- brings an existing row back to this file; demo_url is the owner's to fill and is never
-- touched by a re-run. ⚠ A row added by hand under an id this file does not use, whose name
-- matches one here case-insensitively, makes the insert FAIL on the unique name index —
-- loudly, rather than leaving two moves with one name.
--
-- Reads are public (the library is not private; the website shipped it in a static file).
-- There is no write policy: writes are the service role's and this file's.

create table if not exists public.exercise_library (
  id text primary key check (id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) between 1 and 120),
  muscle text not null,
  equipment text not null,
  category text not null check (category in ('strength', 'power', 'conditioning', 'mobility')),
  -- A demo clip, when one exists. https only, like every other video field the coach tools
  -- render (ShapeWorkoutDocument.videoUrl refuses anything else).
  demo_url text check (demo_url is null or demo_url ~ '^https://'),
  aliases text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

-- One move per name, whatever its case.
create unique index if not exists exercise_library_name_lower_uidx
  on public.exercise_library (lower(name));

alter table public.exercise_library enable row level security;

drop policy if exists "exercise library is public" on public.exercise_library;
create policy "exercise library is public"
  on public.exercise_library for select
  to anon, authenticated
  using (true);

insert into public.exercise_library (id, name, muscle, equipment, category, aliases) values
  ('back-squat', 'Back squat', 'Quads', 'Barbell', 'strength', array['Squat', 'Barbell squat', 'High-bar squat', 'Low-bar squat']::text[]),  -- the 75 built-in moves (dashBuilderCore.js EXERCISES), in their own order
  ('front-squat', 'Front squat', 'Quads', 'Barbell', 'strength', '{}'::text[]),
  ('goblet-squat', 'Goblet squat', 'Quads', 'Dumbbell', 'strength', array['KB goblet squat']::text[]),
  ('hack-squat', 'Hack squat', 'Quads', 'Machine', 'strength', '{}'::text[]),
  ('leg-press', 'Leg press', 'Quads', 'Machine', 'strength', '{}'::text[]),
  ('walking-lunge', 'Walking lunge', 'Quads', 'Dumbbell', 'strength', array['DB walking lunge']::text[]),
  ('split-squat', 'Split squat', 'Quads', 'Dumbbell', 'strength', array['Static lunge']::text[]),
  ('leg-extension', 'Leg extension', 'Quads', 'Machine', 'strength', array['Quad extension']::text[]),
  ('deadlift', 'Deadlift', 'Posterior chain', 'Barbell', 'strength', array['Conventional deadlift', 'DL']::text[]),
  ('romanian-deadlift', 'Romanian deadlift', 'Hamstrings', 'Barbell', 'strength', array['RDL', 'Barbell RDL']::text[]),
  ('trap-bar-deadlift', 'Trap-bar deadlift', 'Posterior chain', 'Trap bar', 'strength', array['Hex bar deadlift']::text[]),
  ('good-morning', 'Good morning', 'Hamstrings', 'Barbell', 'strength', '{}'::text[]),
  ('leg-curl', 'Leg curl', 'Hamstrings', 'Machine', 'strength', array['Hamstring curl']::text[]),
  ('nordic-curl', 'Nordic curl', 'Hamstrings', 'Bodyweight', 'strength', array['Nordic hamstring curl', 'Nordics']::text[]),
  ('hip-thrust', 'Hip thrust', 'Glutes', 'Barbell', 'strength', array['Barbell hip thrust']::text[]),
  ('glute-bridge', 'Glute bridge', 'Glutes', 'Bodyweight', 'strength', array['Bridge']::text[]),
  ('back-extension', 'Back extension', 'Posterior chain', 'Bodyweight', 'strength', array['Hyperextension', '45-degree back extension']::text[]),
  ('standing-calf-raise', 'Standing calf raise', 'Calves', 'Machine', 'strength', '{}'::text[]),
  ('seated-calf-raise', 'Seated calf raise', 'Calves', 'Machine', 'strength', '{}'::text[]),
  ('bench-press', 'Bench press', 'Chest', 'Barbell', 'strength', array['Bench', 'Flat bench', 'Barbell bench press', 'BB bench']::text[]),
  ('incline-bench-press', 'Incline bench press', 'Chest', 'Barbell', 'strength', array['Incline bench', 'Incline barbell press']::text[]),
  ('dumbbell-bench-press', 'Dumbbell bench press', 'Chest', 'Dumbbell', 'strength', array['DB bench', 'DB bench press']::text[]),
  ('incline-dumbbell-press', 'Incline dumbbell press', 'Chest', 'Dumbbell', 'strength', array['Incline DB press', 'Incline dumbbell bench']::text[]),
  ('machine-chest-press', 'Machine chest press', 'Chest', 'Machine', 'strength', array['Chest press']::text[]),
  ('push-up', 'Push-up', 'Chest', 'Bodyweight', 'strength', array['Pushup', 'Press-up']::text[]),
  ('dip', 'Dip', 'Chest', 'Bodyweight', 'strength', array['Dips', 'Parallel bar dip']::text[]),
  ('cable-fly', 'Cable fly', 'Chest', 'Cable', 'strength', array['Cable crossover', 'Cable flye']::text[]),
  ('overhead-press', 'Overhead press', 'Shoulders', 'Barbell', 'strength', array['OHP', 'Military press', 'Strict press', 'Barbell shoulder press']::text[]),
  ('dumbbell-shoulder-press', 'Dumbbell shoulder press', 'Shoulders', 'Dumbbell', 'strength', array['DB shoulder press', 'Seated dumbbell press']::text[]),
  ('lateral-raise', 'Lateral raise', 'Shoulders', 'Dumbbell', 'strength', array['Side raise', 'DB lateral raise']::text[]),
  ('rear-delt-fly', 'Rear-delt fly', 'Shoulders', 'Dumbbell', 'strength', array['Reverse fly', 'Rear delt raise']::text[]),
  ('face-pull', 'Face pull', 'Shoulders', 'Cable', 'strength', '{}'::text[]),
  ('pull-up', 'Pull-up', 'Back', 'Bodyweight', 'strength', array['Pullup']::text[]),
  ('chin-up', 'Chin-up', 'Back', 'Bodyweight', 'strength', array['Chinup']::text[]),
  ('lat-pulldown', 'Lat pulldown', 'Back', 'Cable', 'strength', array['Pulldown']::text[]),
  ('barbell-row', 'Barbell row', 'Back', 'Barbell', 'strength', array['Bent-over row', 'BB row']::text[]),
  ('dumbbell-row', 'Dumbbell row', 'Back', 'Dumbbell', 'strength', array['DB row', 'One-arm row', 'Single-arm dumbbell row']::text[]),
  ('chest-supported-row', 'Chest-supported row', 'Back', 'Machine', 'strength', array['Incline dumbbell row']::text[]),
  ('cable-row', 'Cable row', 'Back', 'Cable', 'strength', array['Seated row', 'Seated cable row']::text[]),
  ('inverted-row', 'Inverted row', 'Back', 'Bodyweight', 'strength', array['Bodyweight row', 'Australian pull-up']::text[]),
  ('shrug', 'Shrug', 'Traps', 'Dumbbell', 'strength', array['Dumbbell shrug']::text[]),
  ('barbell-curl', 'Barbell curl', 'Biceps', 'Barbell', 'strength', array['BB curl', 'Straight-bar curl']::text[]),
  ('dumbbell-curl', 'Dumbbell curl', 'Biceps', 'Dumbbell', 'strength', array['DB curl']::text[]),
  ('hammer-curl', 'Hammer curl', 'Biceps', 'Dumbbell', 'strength', '{}'::text[]),
  ('incline-curl', 'Incline curl', 'Biceps', 'Dumbbell', 'strength', array['Incline dumbbell curl']::text[]),
  ('cable-curl', 'Cable curl', 'Biceps', 'Cable', 'strength', '{}'::text[]),
  ('triceps-pushdown', 'Triceps pushdown', 'Triceps', 'Cable', 'strength', array['Tricep pushdown', 'Pushdown']::text[]),
  ('overhead-triceps-extension', 'Overhead triceps extension', 'Triceps', 'Cable', 'strength', array['Overhead tricep extension', 'Cable overhead extension']::text[]),
  ('skull-crusher', 'Skull crusher', 'Triceps', 'Barbell', 'strength', array['Lying triceps extension', 'Skullcrusher']::text[]),
  ('close-grip-bench', 'Close-grip bench', 'Triceps', 'Barbell', 'strength', array['Close-grip bench press', 'CGBP']::text[]),
  ('plank', 'Plank', 'Core', 'Bodyweight', 'strength', array['Front plank']::text[]),
  ('hanging-leg-raise', 'Hanging leg raise', 'Core', 'Bodyweight', 'strength', array['HLR']::text[]),
  ('ab-wheel-rollout', 'Ab wheel rollout', 'Core', 'Wheel', 'strength', array['Ab wheel', 'Rollout']::text[]),
  ('cable-crunch', 'Cable crunch', 'Core', 'Cable', 'strength', array['Kneeling cable crunch']::text[]),
  ('pallof-press', 'Pallof press', 'Core', 'Cable', 'strength', '{}'::text[]),
  ('farmer-carry', 'Farmer carry', 'Core', 'Dumbbell', 'strength', array['Farmer''s walk', 'Farmer''s carry']::text[]),
  ('suitcase-carry', 'Suitcase carry', 'Core', 'Dumbbell', 'strength', '{}'::text[]),
  ('bird-dog', 'Bird dog', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('dead-bug', 'Dead bug', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('kettlebell-swing', 'Kettlebell swing', 'Posterior chain', 'Kettlebell', 'power', array['KB swing', 'Russian swing']::text[]),
  ('box-jump', 'Box jump', 'Quads', 'Box', 'power', '{}'::text[]),
  ('sled-push', 'Sled push', 'Conditioning', 'Sled', 'conditioning', '{}'::text[]),
  ('assault-bike', 'Assault bike', 'Conditioning', 'Bike', 'conditioning', array['Air bike', 'Fan bike']::text[]),
  ('rower', 'Rower', 'Conditioning', 'Rower', 'conditioning', array['Row erg', 'Rowing machine']::text[]),
  ('easy-run', 'Easy run', 'Conditioning', 'None', 'conditioning', array['Easy jog', 'Jog']::text[]),
  ('tempo-run', 'Tempo run', 'Conditioning', 'None', 'conditioning', '{}'::text[]),
  ('interval-run', 'Interval run', 'Conditioning', 'None', 'conditioning', array['Run intervals']::text[]),
  ('hill-sprints', 'Hill sprints', 'Conditioning', 'None', 'conditioning', array['Hill repeats']::text[]),
  ('jump-rope', 'Jump rope', 'Conditioning', 'Rope', 'conditioning', array['Skipping', 'Skip rope']::text[]),
  ('band-pull-apart', 'Band pull-apart', 'Shoulders', 'Band', 'strength', array['Pull-apart']::text[]),
  ('hip-90-90-flow', 'Hip 90/90 flow', 'Mobility', 'Bodyweight', 'mobility', array['90/90', '90/90 hip switch']::text[]),
  ('couch-stretch', 'Couch stretch', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('worlds-greatest-stretch', 'World''s greatest stretch', 'Mobility', 'Bodyweight', 'mobility', array['WGS']::text[]),
  ('cat-cow', 'Cat-cow', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('glute-med-kickout', 'Glute med kickout', 'Glutes', 'Band', 'strength', '{}'::text[]),
  ('bulgarian-split-squat', 'Bulgarian split squat', 'Quads', 'Dumbbell', 'strength', array['Rear-foot-elevated split squat', 'RFESS']::text[]),  -- the broader set
  ('step-up', 'Step-up', 'Quads', 'Dumbbell', 'strength', array['Box step-up']::text[]),
  ('reverse-lunge', 'Reverse lunge', 'Quads', 'Dumbbell', 'strength', '{}'::text[]),
  ('lateral-lunge', 'Lateral lunge', 'Adductors', 'Bodyweight', 'strength', array['Side lunge']::text[]),
  ('curtsy-lunge', 'Curtsy lunge', 'Glutes', 'Bodyweight', 'strength', '{}'::text[]),
  ('box-squat', 'Box squat', 'Quads', 'Barbell', 'strength', '{}'::text[]),
  ('pause-squat', 'Pause squat', 'Quads', 'Barbell', 'strength', array['Paused squat']::text[]),
  ('zercher-squat', 'Zercher squat', 'Quads', 'Barbell', 'strength', '{}'::text[]),
  ('overhead-squat', 'Overhead squat', 'Quads', 'Barbell', 'strength', array['OHS']::text[]),
  ('safety-bar-squat', 'Safety-bar squat', 'Quads', 'Safety bar', 'strength', array['SSB squat']::text[]),
  ('belt-squat', 'Belt squat', 'Quads', 'Machine', 'strength', '{}'::text[]),
  ('pendulum-squat', 'Pendulum squat', 'Quads', 'Machine', 'strength', '{}'::text[]),
  ('smith-machine-squat', 'Smith machine squat', 'Quads', 'Smith machine', 'strength', '{}'::text[]),
  ('landmine-squat', 'Landmine squat', 'Quads', 'Landmine', 'strength', '{}'::text[]),
  ('pistol-squat', 'Pistol squat', 'Quads', 'Bodyweight', 'strength', '{}'::text[]),
  ('sissy-squat', 'Sissy squat', 'Quads', 'Bodyweight', 'strength', '{}'::text[]),
  ('cossack-squat', 'Cossack squat', 'Adductors', 'Bodyweight', 'strength', '{}'::text[]),
  ('wall-sit', 'Wall sit', 'Quads', 'Bodyweight', 'strength', array['Wall squat']::text[]),
  ('sumo-deadlift', 'Sumo deadlift', 'Posterior chain', 'Barbell', 'strength', '{}'::text[]),
  ('deficit-deadlift', 'Deficit deadlift', 'Posterior chain', 'Barbell', 'strength', '{}'::text[]),
  ('rack-pull', 'Rack pull', 'Posterior chain', 'Barbell', 'strength', array['Block pull']::text[]),
  ('snatch-grip-deadlift', 'Snatch-grip deadlift', 'Posterior chain', 'Barbell', 'strength', '{}'::text[]),
  ('stiff-leg-deadlift', 'Stiff-leg deadlift', 'Hamstrings', 'Barbell', 'strength', array['SLDL']::text[]),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian deadlift', 'Hamstrings', 'Dumbbell', 'strength', array['DB RDL']::text[]),
  ('single-leg-romanian-deadlift', 'Single-leg Romanian deadlift', 'Hamstrings', 'Dumbbell', 'strength', array['Single-leg RDL', 'SL RDL']::text[]),
  ('kettlebell-deadlift', 'Kettlebell deadlift', 'Posterior chain', 'Kettlebell', 'strength', array['KB deadlift']::text[]),
  ('seated-leg-curl', 'Seated leg curl', 'Hamstrings', 'Machine', 'strength', '{}'::text[]),
  ('lying-leg-curl', 'Lying leg curl', 'Hamstrings', 'Machine', 'strength', array['Prone leg curl']::text[]),
  ('glute-ham-raise', 'Glute-ham raise', 'Hamstrings', 'Machine', 'strength', array['GHR']::text[]),
  ('stability-ball-leg-curl', 'Stability ball leg curl', 'Hamstrings', 'Stability ball', 'strength', array['Swiss ball leg curl']::text[]),
  ('reverse-hyperextension', 'Reverse hyperextension', 'Posterior chain', 'Machine', 'strength', array['Reverse hyper']::text[]),
  ('cable-pull-through', 'Cable pull-through', 'Glutes', 'Cable', 'strength', '{}'::text[]),
  ('single-leg-hip-thrust', 'Single-leg hip thrust', 'Glutes', 'Bodyweight', 'strength', '{}'::text[]),
  ('glute-kickback', 'Glute kickback', 'Glutes', 'Cable', 'strength', array['Cable kickback']::text[]),
  ('frog-pump', 'Frog pump', 'Glutes', 'Bodyweight', 'strength', '{}'::text[]),
  ('hip-abduction', 'Hip abduction', 'Glutes', 'Machine', 'strength', array['Abductor machine']::text[]),
  ('hip-adduction', 'Hip adduction', 'Adductors', 'Machine', 'strength', array['Adductor machine']::text[]),
  ('banded-lateral-walk', 'Banded lateral walk', 'Glutes', 'Band', 'strength', array['Monster walk', 'Band walk']::text[]),
  ('clamshell', 'Clamshell', 'Glutes', 'Band', 'strength', '{}'::text[]),
  ('copenhagen-plank', 'Copenhagen plank', 'Adductors', 'Bodyweight', 'strength', array['Copenhagen side plank']::text[]),
  ('single-leg-calf-raise', 'Single-leg calf raise', 'Calves', 'Dumbbell', 'strength', '{}'::text[]),
  ('donkey-calf-raise', 'Donkey calf raise', 'Calves', 'Machine', 'strength', '{}'::text[]),
  ('decline-bench-press', 'Decline bench press', 'Chest', 'Barbell', 'strength', array['Decline bench']::text[]),
  ('floor-press', 'Floor press', 'Chest', 'Barbell', 'strength', '{}'::text[]),
  ('smith-machine-bench-press', 'Smith machine bench press', 'Chest', 'Smith machine', 'strength', '{}'::text[]),
  ('dumbbell-fly', 'Dumbbell fly', 'Chest', 'Dumbbell', 'strength', array['DB fly', 'Dumbbell flye']::text[]),
  ('incline-dumbbell-fly', 'Incline dumbbell fly', 'Chest', 'Dumbbell', 'strength', array['Incline DB fly']::text[]),
  ('pec-deck', 'Pec deck', 'Chest', 'Machine', 'strength', array['Machine fly', 'Pec fly']::text[]),
  ('incline-push-up', 'Incline push-up', 'Chest', 'Bodyweight', 'strength', '{}'::text[]),
  ('decline-push-up', 'Decline push-up', 'Chest', 'Bodyweight', 'strength', array['Feet-elevated push-up']::text[]),
  ('close-grip-push-up', 'Close-grip push-up', 'Triceps', 'Bodyweight', 'strength', array['Diamond push-up']::text[]),
  ('arnold-press', 'Arnold press', 'Shoulders', 'Dumbbell', 'strength', '{}'::text[]),
  ('push-press', 'Push press', 'Shoulders', 'Barbell', 'power', '{}'::text[]),
  ('push-jerk', 'Push jerk', 'Shoulders', 'Barbell', 'power', '{}'::text[]),
  ('z-press', 'Z press', 'Shoulders', 'Barbell', 'strength', '{}'::text[]),
  ('machine-shoulder-press', 'Machine shoulder press', 'Shoulders', 'Machine', 'strength', '{}'::text[]),
  ('landmine-press', 'Landmine press', 'Shoulders', 'Landmine', 'strength', '{}'::text[]),
  ('kettlebell-press', 'Kettlebell press', 'Shoulders', 'Kettlebell', 'strength', array['KB press']::text[]),
  ('cable-lateral-raise', 'Cable lateral raise', 'Shoulders', 'Cable', 'strength', '{}'::text[]),
  ('front-raise', 'Front raise', 'Shoulders', 'Dumbbell', 'strength', '{}'::text[]),
  ('upright-row', 'Upright row', 'Shoulders', 'Barbell', 'strength', '{}'::text[]),
  ('reverse-pec-deck', 'Reverse pec deck', 'Shoulders', 'Machine', 'strength', array['Reverse machine fly']::text[]),
  ('y-raise', 'Y-raise', 'Shoulders', 'Dumbbell', 'strength', array['Incline Y-raise']::text[]),
  ('cable-external-rotation', 'Cable external rotation', 'Shoulders', 'Cable', 'strength', '{}'::text[]),
  ('pike-push-up', 'Pike push-up', 'Shoulders', 'Bodyweight', 'strength', '{}'::text[]),
  ('handstand-push-up', 'Handstand push-up', 'Shoulders', 'Bodyweight', 'strength', array['HSPU']::text[]),
  ('pendlay-row', 'Pendlay row', 'Back', 'Barbell', 'strength', '{}'::text[]),
  ('seal-row', 'Seal row', 'Back', 'Barbell', 'strength', '{}'::text[]),
  ('t-bar-row', 'T-bar row', 'Back', 'Landmine', 'strength', array['Landmine row']::text[]),
  ('meadows-row', 'Meadows row', 'Back', 'Landmine', 'strength', '{}'::text[]),
  ('single-arm-cable-row', 'Single-arm cable row', 'Back', 'Cable', 'strength', '{}'::text[]),
  ('renegade-row', 'Renegade row', 'Back', 'Dumbbell', 'strength', '{}'::text[]),
  ('ring-row', 'Ring row', 'Back', 'Rings', 'strength', '{}'::text[]),
  ('close-grip-lat-pulldown', 'Close-grip lat pulldown', 'Back', 'Cable', 'strength', array['Close-grip pulldown']::text[]),
  ('straight-arm-pulldown', 'Straight-arm pulldown', 'Back', 'Cable', 'strength', array['Straight-arm lat pulldown', 'Cable pullover']::text[]),
  ('dumbbell-pullover', 'Dumbbell pullover', 'Back', 'Dumbbell', 'strength', array['DB pullover']::text[]),
  ('neutral-grip-pull-up', 'Neutral-grip pull-up', 'Back', 'Bodyweight', 'strength', '{}'::text[]),
  ('assisted-pull-up', 'Assisted pull-up', 'Back', 'Machine', 'strength', '{}'::text[]),
  ('scapular-pull-up', 'Scapular pull-up', 'Back', 'Bodyweight', 'strength', array['Scap pull-up']::text[]),
  ('barbell-shrug', 'Barbell shrug', 'Traps', 'Barbell', 'strength', '{}'::text[]),
  ('ez-bar-curl', 'EZ-bar curl', 'Biceps', 'EZ bar', 'strength', '{}'::text[]),
  ('preacher-curl', 'Preacher curl', 'Biceps', 'EZ bar', 'strength', '{}'::text[]),
  ('concentration-curl', 'Concentration curl', 'Biceps', 'Dumbbell', 'strength', '{}'::text[]),
  ('spider-curl', 'Spider curl', 'Biceps', 'Dumbbell', 'strength', '{}'::text[]),
  ('bayesian-curl', 'Bayesian curl', 'Biceps', 'Cable', 'strength', '{}'::text[]),
  ('zottman-curl', 'Zottman curl', 'Biceps', 'Dumbbell', 'strength', '{}'::text[]),
  ('reverse-curl', 'Reverse curl', 'Forearms', 'Barbell', 'strength', '{}'::text[]),
  ('rope-pushdown', 'Rope pushdown', 'Triceps', 'Cable', 'strength', array['Rope triceps pushdown']::text[]),
  ('dumbbell-overhead-triceps-extension', 'Dumbbell overhead triceps extension', 'Triceps', 'Dumbbell', 'strength', array['DB overhead extension']::text[]),
  ('triceps-kickback', 'Triceps kickback', 'Triceps', 'Dumbbell', 'strength', array['Tricep kickback']::text[]),
  ('bench-dip', 'Bench dip', 'Triceps', 'Bodyweight', 'strength', '{}'::text[]),
  ('jm-press', 'JM press', 'Triceps', 'Barbell', 'strength', '{}'::text[]),
  ('wrist-curl', 'Wrist curl', 'Forearms', 'Dumbbell', 'strength', '{}'::text[]),
  ('reverse-wrist-curl', 'Reverse wrist curl', 'Forearms', 'Dumbbell', 'strength', '{}'::text[]),
  ('dead-hang', 'Dead hang', 'Forearms', 'Bodyweight', 'strength', array['Bar hang']::text[]),
  ('plate-pinch', 'Plate pinch', 'Forearms', 'Plate', 'strength', '{}'::text[]),
  ('side-plank', 'Side plank', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('hollow-hold', 'Hollow hold', 'Core', 'Bodyweight', 'strength', array['Hollow body hold']::text[]),
  ('crunch', 'Crunch', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('reverse-crunch', 'Reverse crunch', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('bicycle-crunch', 'Bicycle crunch', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('sit-up', 'Sit-up', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('v-up', 'V-up', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('russian-twist', 'Russian twist', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('hanging-knee-raise', 'Hanging knee raise', 'Core', 'Bodyweight', 'strength', '{}'::text[]),
  ('toes-to-bar', 'Toes-to-bar', 'Core', 'Bodyweight', 'strength', array['T2B']::text[]),
  ('cable-woodchop', 'Cable woodchop', 'Core', 'Cable', 'strength', array['Woodchopper']::text[]),
  ('landmine-rotation', 'Landmine rotation', 'Core', 'Landmine', 'strength', '{}'::text[]),
  ('stir-the-pot', 'Stir the pot', 'Core', 'Stability ball', 'strength', '{}'::text[]),
  ('overhead-carry', 'Overhead carry', 'Core', 'Kettlebell', 'strength', array['Waiter carry']::text[]),
  ('mountain-climber', 'Mountain climber', 'Core', 'Bodyweight', 'conditioning', '{}'::text[]),
  ('bear-crawl', 'Bear crawl', 'Core', 'Bodyweight', 'conditioning', '{}'::text[]),
  ('power-clean', 'Power clean', 'Full body', 'Barbell', 'power', '{}'::text[]),
  ('hang-clean', 'Hang clean', 'Full body', 'Barbell', 'power', '{}'::text[]),
  ('clean-and-jerk', 'Clean and jerk', 'Full body', 'Barbell', 'power', '{}'::text[]),
  ('power-snatch', 'Power snatch', 'Full body', 'Barbell', 'power', '{}'::text[]),
  ('clean-pull', 'Clean pull', 'Posterior chain', 'Barbell', 'power', '{}'::text[]),
  ('high-pull', 'High pull', 'Traps', 'Barbell', 'power', '{}'::text[]),
  ('dumbbell-snatch', 'Dumbbell snatch', 'Full body', 'Dumbbell', 'power', array['DB snatch']::text[]),
  ('kettlebell-snatch', 'Kettlebell snatch', 'Full body', 'Kettlebell', 'power', array['KB snatch']::text[]),
  ('kettlebell-clean', 'Kettlebell clean', 'Full body', 'Kettlebell', 'power', array['KB clean']::text[]),
  ('medicine-ball-slam', 'Medicine ball slam', 'Full body', 'Medicine ball', 'power', array['Ball slam', 'Med ball slam']::text[]),
  ('medicine-ball-chest-pass', 'Medicine ball chest pass', 'Chest', 'Medicine ball', 'power', array['Med ball chest pass']::text[]),
  ('rotational-medicine-ball-throw', 'Rotational medicine ball throw', 'Core', 'Medicine ball', 'power', array['Med ball rotational throw']::text[]),
  ('broad-jump', 'Broad jump', 'Posterior chain', 'Bodyweight', 'power', array['Standing long jump']::text[]),
  ('depth-jump', 'Depth jump', 'Quads', 'Box', 'power', '{}'::text[]),
  ('jump-squat', 'Jump squat', 'Quads', 'Bodyweight', 'power', array['Squat jump']::text[]),
  ('tuck-jump', 'Tuck jump', 'Quads', 'Bodyweight', 'power', '{}'::text[]),
  ('lateral-bound', 'Lateral bound', 'Glutes', 'Bodyweight', 'power', array['Skater jump']::text[]),
  ('thruster', 'Thruster', 'Full body', 'Barbell', 'strength', '{}'::text[]),
  ('turkish-get-up', 'Turkish get-up', 'Full body', 'Kettlebell', 'strength', array['TGU', 'Get-up']::text[]),
  ('sandbag-carry', 'Sandbag carry', 'Full body', 'Sandbag', 'strength', '{}'::text[]),
  ('sled-drag', 'Sled drag', 'Conditioning', 'Sled', 'conditioning', '{}'::text[]),
  ('burpee', 'Burpee', 'Full body', 'Bodyweight', 'conditioning', '{}'::text[]),
  ('wall-ball', 'Wall ball', 'Full body', 'Medicine ball', 'conditioning', array['Wall ball shot']::text[]),
  ('jumping-jack', 'Jumping jack', 'Conditioning', 'Bodyweight', 'conditioning', '{}'::text[]),
  ('high-knees', 'High knees', 'Conditioning', 'Bodyweight', 'conditioning', '{}'::text[]),
  ('double-under', 'Double-under', 'Conditioning', 'Rope', 'conditioning', '{}'::text[]),
  ('battle-rope-waves', 'Battle rope waves', 'Conditioning', 'Battle rope', 'conditioning', array['Battle ropes']::text[]),
  ('ski-machine', 'Ski machine', 'Conditioning', 'Ski machine', 'conditioning', array['Ski erg']::text[]),
  ('stationary-bike', 'Stationary bike', 'Conditioning', 'Bike', 'conditioning', array['Exercise bike', 'Spin bike']::text[]),
  ('stair-climber', 'Stair climber', 'Conditioning', 'Machine', 'conditioning', array['Stair stepper']::text[]),
  ('elliptical', 'Elliptical', 'Conditioning', 'Machine', 'conditioning', array['Cross-trainer']::text[]),
  ('treadmill-run', 'Treadmill run', 'Conditioning', 'Treadmill', 'conditioning', '{}'::text[]),
  ('incline-walk', 'Incline walk', 'Conditioning', 'Treadmill', 'conditioning', array['Incline treadmill walk']::text[]),
  ('long-run', 'Long run', 'Conditioning', 'None', 'conditioning', '{}'::text[]),
  ('fartlek', 'Fartlek', 'Conditioning', 'None', 'conditioning', '{}'::text[]),
  ('sprint', 'Sprint', 'Conditioning', 'None', 'conditioning', array['Flat sprint']::text[]),
  ('shuttle-run', 'Shuttle run', 'Conditioning', 'None', 'conditioning', '{}'::text[]),
  ('walk', 'Walk', 'Conditioning', 'None', 'conditioning', array['Brisk walk']::text[]),
  ('ruck', 'Ruck', 'Conditioning', 'Rucksack', 'conditioning', array['Rucking']::text[]),
  ('swim', 'Swim', 'Conditioning', 'Pool', 'conditioning', '{}'::text[]),
  ('hip-flexor-stretch', 'Hip flexor stretch', 'Mobility', 'Bodyweight', 'mobility', array['Kneeling hip flexor stretch']::text[]),
  ('pigeon-stretch', 'Pigeon stretch', 'Mobility', 'Bodyweight', 'mobility', array['Pigeon pose']::text[]),
  ('hamstring-stretch', 'Hamstring stretch', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('calf-stretch', 'Calf stretch', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('pec-stretch', 'Pec stretch', 'Mobility', 'Bodyweight', 'mobility', array['Doorway pec stretch']::text[]),
  ('lat-stretch', 'Lat stretch', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('frog-stretch', 'Frog stretch', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('thoracic-rotation', 'Thoracic rotation', 'Mobility', 'Bodyweight', 'mobility', array['Open book', 'T-spine rotation']::text[]),
  ('thread-the-needle', 'Thread the needle', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('childs-pose', 'Child''s pose', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('downward-dog', 'Downward dog', 'Mobility', 'Bodyweight', 'mobility', array['Down dog']::text[]),
  ('deep-squat-hold', 'Deep squat hold', 'Mobility', 'Bodyweight', 'mobility', array['Squat hold']::text[]),
  ('ankle-rocks', 'Ankle rocks', 'Mobility', 'Bodyweight', 'mobility', array['Knee-to-wall']::text[]),
  ('shoulder-dislocate', 'Shoulder dislocate', 'Mobility', 'Band', 'mobility', array['Band pass-through']::text[]),
  ('wall-slide', 'Wall slide', 'Mobility', 'Bodyweight', 'mobility', array['Wall angel']::text[]),
  ('leg-swings', 'Leg swings', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('arm-circles', 'Arm circles', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('inchworm', 'Inchworm', 'Mobility', 'Bodyweight', 'mobility', '{}'::text[]),
  ('spiderman-lunge', 'Spiderman lunge', 'Mobility', 'Bodyweight', 'mobility', array['Spiderman stretch']::text[]),
  ('jefferson-curl', 'Jefferson curl', 'Mobility', 'Dumbbell', 'mobility', '{}'::text[]),
  ('foam-roll', 'Foam roll', 'Mobility', 'Foam roller', 'mobility', array['Foam rolling']::text[])
on conflict (id) do update set
  name = excluded.name,
  muscle = excluded.muscle,
  equipment = excluded.equipment,
  category = excluded.category,
  aliases = excluded.aliases;
