// Nutritionist playlists — for clients while cooking / prepping / eating.
// Same structure as trainer playlists but attached to meals/recipes/plans.
const NUTRI_PLAYLISTS = [
  {
    id: "npl-sunday",
    name: "Sunday Meal Prep",
    provider: "spotify",
    url: "https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M",
    note: "2 hours. Enough to get through batch cooking without burning out.",
    bpm: "95–120",
    trackCount: 32,
    duration: "2h 18m",
    cover: "linear-gradient(135deg, #6a4a1c 0%, #1a1612 70%)",
    accent: "#f2a94e",
    attachedTo: ["mp-batch-proteins", "mp-overnight-oats", "mp-veggie-prep"],
    shared: true,
    updated: "3d ago",
    listens: 1284,
    sampleTracks: [
      ["Khruangbin", "Maria También", "4:58"],
      ["Mild High Club", "Homage", "3:40"],
      ["Unknown Mortal Orchestra", "Multi-Love", "4:26"],
      ["Mac DeMarco", "Chamber of Reflection", "4:42"],
      ["Men I Trust", "Show Me How", "3:51"],
    ],
  },
  {
    id: "npl-weeknight",
    name: "Weeknight Dinner (30 min)",
    provider: "spotify",
    url: "https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO",
    note: "Upbeat but not frantic. Ends right as dinner hits the table.",
    bpm: "100–128",
    trackCount: 12,
    duration: "32 min",
    cover: "linear-gradient(135deg, #5a2a4a 0%, #1a1612 70%)",
    accent: "#e86bd8",
    attachedTo: ["rcp-sheet-pan-salmon", "rcp-chicken-stirfry", "rcp-grain-bowl"],
    shared: true,
    updated: "Yesterday",
    listens: 896,
    sampleTracks: [
      ["Vulfpeck", "Back Pocket", "2:28"],
      ["Lake Street Dive", "Good Kisser", "3:58"],
      ["Chromeo", "Fancy Footwork", "3:47"],
      ["Jungle", "Busy Earnin'", "3:12"],
      ["Tom Misch", "Movie", "4:34"],
    ],
  },
  {
    id: "npl-slow",
    name: "Slow Sunday Braise",
    provider: "apple",
    url: "https://music.apple.com/us/playlist/slow-sunday/pl.u-GgA5pbMfM5V3LW",
    note: "Low-and-slow jazz. For when you've got 3 hours and a Dutch oven.",
    bpm: "60–95",
    trackCount: 28,
    duration: "2h 48m",
    cover: "linear-gradient(135deg, #3a2a1c 0%, #1a1612 70%)",
    accent: "#c89968",
    attachedTo: ["rcp-braise", "rcp-ragu", "rcp-slow-chili"],
    shared: false,
    updated: "5d ago",
    listens: 218,
    sampleTracks: [
      ["Bill Evans", "Peace Piece", "6:46"],
      ["John Coltrane", "Naima", "4:21"],
      ["Chet Baker", "My Funny Valentine", "2:22"],
      ["Miles Davis", "Blue in Green", "5:37"],
      ["Nina Simone", "Feeling Good", "2:56"],
    ],
  },
  {
    id: "npl-morning",
    name: "Morning Kitchen",
    provider: "spotify",
    url: "https://open.spotify.com/playlist/37i9dQZF1DWZd79rJ6a7lp",
    note: "Gentle start. Protein shake, coffee, overnight oats vibes.",
    bpm: "70–100",
    trackCount: 24,
    duration: "1h 34m",
    cover: "linear-gradient(135deg, #1c4a5a 0%, #1a1612 70%)",
    accent: "#4ab8d8",
    attachedTo: ["rcp-oats", "rcp-smoothie", "mp-breakfast-prep"],
    shared: true,
    updated: "1w ago",
    listens: 742,
    sampleTracks: [
      ["Nujabes", "Aruarian Dance", "3:48"],
      ["FKJ", "Tadow", "4:28"],
      ["Tom Misch", "South of the River", "5:14"],
      ["Rhye", "Open", "4:35"],
      ["Alina Baraz", "Make You Feel", "3:51"],
    ],
  },
  {
    id: "npl-mindful",
    name: "Mindful Eating",
    provider: "spotify",
    url: "https://open.spotify.com/playlist/37i9dQZF1DWZqd5JICZI0u",
    note: "For actually tasting the food. Low stim, phone in the drawer.",
    bpm: "50–80",
    trackCount: 20,
    duration: "1h 22m",
    cover: "linear-gradient(135deg, #1c5a4a 0%, #1a1612 70%)",
    accent: "#1EC0A8",
    attachedTo: ["plan-intuitive", "plan-stress-eating"],
    shared: true,
    updated: "2w ago",
    listens: 512,
    sampleTracks: [
      ["Ludovico Einaudi", "Nuvole Bianche", "5:58"],
      ["Max Richter", "On the Nature of Daylight", "6:14"],
      ["Ólafur Arnalds", "Near Light", "4:22"],
      ["Nils Frahm", "Says", "8:18"],
      ["Hania Rani", "Eden", "5:01"],
    ],
  },
  {
    id: "npl-batch",
    name: "Power-Hour Batch",
    provider: "spotify",
    url: "https://open.spotify.com/playlist/37i9dQZF1DXdxcBWuJkbcy",
    note: "60 min hard charge. Five meals done before it ends.",
    bpm: "120–140",
    trackCount: 15,
    duration: "58 min",
    cover: "linear-gradient(135deg, #7a2a2a 0%, #1a1612 70%)",
    accent: "#d84a4a",
    attachedTo: ["mp-batch-proteins", "plan-cutting"],
    shared: false,
    updated: "4h ago",
    listens: 48,
    sampleTracks: [
      ["Fred again..", "Delilah (pull me out of this)", "4:12"],
      ["Overmono", "So U Kno", "3:58"],
      ["Peggy Gou", "(It Goes Like) Nanana", "3:15"],
      ["Four Tet", "Teenage Birdsong", "4:53"],
      ["Jamie xx", "Gosh", "6:18"],
    ],
  },
];

// Things a nutritionist can attach playlists to — meals, recipes, meal-prep routines, plans.
const NUTRI_ATTACH_TARGETS = [
  { id: "mp-batch-proteins",   name: "Batch Proteins (prep)",       program: "All plans",         duration: "60 min", clientsDoing: 28, kind: "prep" },
  { id: "mp-overnight-oats",   name: "Overnight Oats (5 jars)",     program: "Breakfast",         duration: "15 min", clientsDoing: 22, kind: "prep" },
  { id: "mp-veggie-prep",      name: "Weekly Veggie Wash + Chop",   program: "All plans",         duration: "45 min", clientsDoing: 28, kind: "prep" },
  { id: "mp-breakfast-prep",   name: "Breakfast Mise-en-place",     program: "Breakfast",         duration: "20 min", clientsDoing: 18, kind: "prep" },
  { id: "rcp-sheet-pan-salmon", name: "Sheet-pan salmon + greens",  program: "Performance cut",   duration: "28 min", clientsDoing: 12, kind: "recipe" },
  { id: "rcp-chicken-stirfry", name: "Chicken + veg stir-fry",      program: "Lean bulk",         duration: "22 min", clientsDoing: 14, kind: "recipe" },
  { id: "rcp-grain-bowl",      name: "Mediterranean grain bowl",    program: "Plant-forward",     duration: "18 min", clientsDoing: 9,  kind: "recipe" },
  { id: "rcp-oats",            name: "Savory oats (high-protein)",  program: "Breakfast",         duration: "12 min", clientsDoing: 22, kind: "recipe" },
  { id: "rcp-smoothie",        name: "Post-lift shake",             program: "Performance cut",   duration: "5 min",  clientsDoing: 20, kind: "recipe" },
  { id: "rcp-braise",          name: "Sunday braise (8 portions)",  program: "Batch-friendly",    duration: "3 hr",   clientsDoing: 11, kind: "recipe" },
  { id: "rcp-ragu",            name: "Slow bolognese",              program: "Batch-friendly",    duration: "2h 30m", clientsDoing: 8,  kind: "recipe" },
  { id: "rcp-slow-chili",      name: "Turkey chili (slow cook)",    program: "Batch-friendly",    duration: "4 hr",   clientsDoing: 10, kind: "recipe" },
  { id: "plan-intuitive",      name: "Intuitive eating plan",       program: "Behavioral",        duration: "—",      clientsDoing: 6,  kind: "plan" },
  { id: "plan-stress-eating",  name: "Stress-eating protocol",      program: "Behavioral",        duration: "—",      clientsDoing: 4,  kind: "plan" },
  { id: "plan-cutting",        name: "Performance cut (12 wk)",     program: "Performance cut",   duration: "—",      clientsDoing: 12, kind: "plan" },
];

Object.assign(window, { NUTRI_PLAYLISTS, NUTRI_ATTACH_TARGETS });
