// Shape Kitchen recipe library — shared dataset for the mobile app; the
// website's /recipes (public/newdesign/recipes.jsx) carries a content-parity
// copy (string ingredients, generated from this file — see the Kitchen Card
// wave spec §7.6). Each recipe:
//   by / byRole (Nutritionist | Dietician)
//   diet (Vegan | Vegetarian | Plant-based | Seafood | Poultry | Meat)
//   time: compact total (register-friendly) · prep?: passive/prep note
//   ingredients: { n: qty, m: name, k?: 'NNN kcal' }[]  (structured since the
//     Kitchen Card wave — a real quantity on every line)
//   steps: string[] (cookable: heat · vessel · time · doneness cue)
//   tip: string (renders as the card's typed byline note; storage advice on
//     batch recipes)   photo?: real image URL (figure renders only when set)
//   hero: CSS gradient (tab-era placeholder; never rendered as a photo)
// The 50 USDA MyPlate Kitchen recipes live in their own file: they are US
// federal works (public domain, 17 USC § 105) with every step rewritten in this
// catalog's voice, and keeping them separate keeps their provenance legible and
// this file readable. They carry `source`/`sourceUrl`/`license` INSTEAD of a
// by/byRole byline — see bsRecipeAttribution, which is the single place that
// decides how an unattributed recipe is credited.
import { USDA_KITCHEN_RECIPES, USDA_NOT_GF, USDA_HAS_DAIRY, USDA_MED } from './shapeKitchenData.usda.js';

const _SHAPE_KITCHEN_RECIPES_AUTHORED = [
  {
    title: "One-pan chicken and rice",
    by: "Rae Lindqvist", byRole: "Nutritionist", diet: "Poultry",
    time: "30 min", servings: 1, kcal: 640, macros: { p: 48, c: 72, f: 18 },
    tags: ["High protein", "Pantry", "30 min"],
    hero: "linear-gradient(135deg, #e8b06a 0%, #b46a3c 60%, #1a1612 100%)",
    blurb: "Sunday reset — easy to scale up for meal prep.",
    ingredients: [
      { n: "6 oz", m: "chicken thigh, skin-on", k: "330 kcal" },
      { n: "3/4 cup", m: "jasmine rice", k: "240 kcal" },
      { n: "1 cup", m: "low-sodium chicken broth" },
      { n: "2 cloves", m: "garlic, minced" },
      { n: "1 tsp", m: "smoked paprika" },
      { n: "1/2 tsp", m: "fine salt" },
      { n: "1/2 cup", m: "frozen peas" },
    ],
    steps: [
      "Pat the chicken thigh completely dry and season both sides with the salt and paprika — dry skin is what lets it brown instead of steam.",
      "Heat 1 tsp oil in a small skillet over medium-high. Sear the chicken 3 minutes per side until deeply golden, then lift it onto a plate (it won't be cooked through yet).",
      "Lower the heat to medium, add the minced garlic and rice, and toast for 1 minute, stirring, until the grains smell nutty.",
      "Pour in the broth, scrape up any browned bits from the base, and bring to a gentle simmer.",
      "Nestle the chicken back in, skin-side up, cover tightly, and cook on low for 18 minutes without lifting the lid — it's done when the thickest part hits 165°F.",
      "Stir the frozen peas into the rice, replace the lid, and rest off the heat for 5 minutes. Fork through and serve.",
    ],
    tip: "No lid? Cover the skillet with a plate or foil — trapping the steam is what cooks the rice evenly. Doubles cleanly for two days of lunches; keeps 3 days chilled.",
  },
  {
    title: "Greek yogurt power bowl",
    by: "Mara Whitfield", byRole: "Dietician", diet: "Vegetarian",
    time: "5 min", servings: 1, kcal: 480, macros: { p: 38, c: 52, f: 12 },
    tags: ["High protein", "No-cook", "Breakfast"],
    hero: "linear-gradient(135deg, #f0e0c2 0%, #c9a26a 55%, #1a1612 100%)",
    blurb: "Monday breakfast — sets the protein bar early.",
    ingredients: [
      { n: "1 cup", m: "0% Greek yogurt", k: "130 kcal" },
      { n: "1 scoop", m: "whey protein", k: "120 kcal" },
      { n: "1/2 cup", m: "mixed berries" },
      { n: "2 tbsp", m: "granola" },
      { n: "1 tbsp", m: "peanut butter", k: "95 kcal" },
      { n: "1 tsp", m: "honey" },
    ],
    steps: [
      "Spoon the Greek yogurt into a bowl, add the scoop of whey, and let it sit a few seconds so the powder starts to hydrate.",
      "Whisk hard with a fork for about 30 seconds until the powder fully dissolves and the yogurt turns smooth — add a splash of milk if it gets too thick.",
      "Layer the berries over one half and the granola over the other so the granola stays crunchy.",
      "Warm the peanut butter for 10 seconds so it pours, then drizzle it across the top with the honey.",
      "Eat immediately — granola softens fast once it hits the yogurt.",
    ],
    tip: "Prep the yogurt-whey base the night before; add toppings in the morning so the granola never goes soggy.",
  },
  {
    title: "Tempo turkey lettuce cups",
    by: "Tom Okafor", byRole: "Nutritionist", diet: "Poultry",
    time: "20 min", servings: 1, kcal: 520, macros: { p: 42, c: 38, f: 22 },
    tags: ["Low carb", "Quick"],
    hero: "linear-gradient(135deg, #a3c98c 0%, #5b8a4c 55%, #1a1612 100%)",
    blurb: "Tuesday — quick spin between sessions.",
    ingredients: [
      { n: "6 oz", m: "lean ground turkey", k: "260 kcal" },
      { n: "1 tbsp", m: "soy sauce" },
      { n: "1 tsp", m: "sesame oil" },
      { n: "2 cloves", m: "garlic, minced" },
      { n: "1 tsp", m: "fresh ginger, minced" },
      { n: "8 leaves", m: "butter lettuce" },
      { n: "1", m: "carrot, julienned" },
      { n: "1/2", m: "cucumber, julienned" },
      { n: "to taste", m: "sriracha" },
    ],
    steps: [
      "Separate the butter lettuce into whole cups, rinse, and pat dry — set them on a plate ready to fill so nothing wilts while you cook.",
      "Heat a dry skillet over medium-high. Add the turkey and press it flat; let it sit undisturbed 2 minutes to build a browned crust before breaking it apart.",
      "Push the meat aside, add the garlic and ginger to the bare pan for 30 seconds until fragrant, then mix into the turkey.",
      "Pour in the soy sauce and sesame oil and toss for 1 minute until the liquid glazes the meat and the pan is almost dry.",
      "Spoon the turkey into the lettuce cups, top with the julienned carrot and cucumber, and finish with a zigzag of sriracha.",
    ],
    tip: "Brown the turkey in a thin layer and resist stirring early — that crust is most of the flavour in a low-carb dish.",
  },
  {
    title: "Sheet-pan salmon, sweet potato and broccoli",
    by: "Marco Bellini", byRole: "Nutritionist", diet: "Seafood",
    time: "35 min", servings: 1, kcal: 620, macros: { p: 44, c: 58, f: 22 },
    tags: ["High protein", "GF", "Sheet-pan"],
    hero: "linear-gradient(135deg, #e07856 0%, #f4b860 50%, #1a1612 100%)",
    blurb: "Wednesday dinner — pairs with tonight's lift.",
    ingredients: [
      { n: "6 oz", m: "salmon fillet", k: "310 kcal" },
      { n: "1 medium", m: "sweet potato, cubed", k: "115 kcal" },
      { n: "2 cups", m: "broccoli florets" },
      { n: "2 tbsp", m: "olive oil" },
      { n: "1 tsp", m: "paprika" },
      { n: "1/2 tsp", m: "salt, plus pepper" },
      { n: "1", m: "lemon, sliced" },
    ],
    steps: [
      "Heat the oven to 425°F (220°C) and line a sheet pan with parchment so nothing sticks.",
      "Toss the sweet potato cubes with 1 tbsp oil, the paprika, salt and pepper, spread them out, and roast 15 minutes — a head start so they finish with the fish.",
      "Meanwhile, pat the salmon dry and rub it with a little oil, salt and pepper so it roasts instead of steaming.",
      "Pull the pan out, push the potatoes to one side, and add the broccoli and salmon. Drizzle the remaining oil over the broccoli and lay lemon slices on the fish.",
      "Roast another 12–15 minutes, until the broccoli edges char and the salmon flakes when nudged (internal temp ~125°F for medium).",
      "Squeeze the roasted lemon over everything and serve straight from the pan.",
    ],
    tip: "Cut the sweet potato into even 3/4-inch cubes so none are raw while others turn to mush.",
  },
  {
    title: "Steak and sweet potato hash",
    by: "Daniel Reyes", byRole: "Dietician", diet: "Meat",
    time: "25 min", prep: "15 min temper", servings: 1, kcal: 660, macros: { p: 46, c: 56, f: 26 },
    tags: ["High protein", "Iron-rich"],
    hero: "linear-gradient(135deg, #8b3a28 0%, #c95a3c 55%, #1a1612 100%)",
    blurb: "Thursday — leg-day refuel.",
    ingredients: [
      { n: "6 oz", m: "sirloin steak", k: "340 kcal" },
      { n: "1", m: "sweet potato, diced small", k: "115 kcal" },
      { n: "1/2", m: "onion, sliced" },
      { n: "1", m: "bell pepper, diced" },
      { n: "1 tbsp", m: "olive oil" },
      { n: "1/2 tsp", m: "garlic powder" },
      { n: "1/2 tsp", m: "smoked paprika" },
    ],
    steps: [
      "Take the steak out of the fridge 15 minutes ahead and season generously with salt — room-temperature meat sears more evenly.",
      "Heat the oil in a skillet over medium. Add the small-diced sweet potato in a single layer and cook 8 minutes, covered, stirring occasionally, until tender with crisp edges.",
      "Add the onion, bell pepper, garlic powder and smoked paprika; cook 5 more minutes until softened and caramelised. Scrape the hash onto a plate.",
      "Turn the heat to high. Sear the steak 3 minutes per side for medium-rare, pressing it down for full contact.",
      "Rest the steak on a board for 4 minutes, then slice it thinly against the grain.",
      "Pile the hash back in the warm pan, fan the steak over the top, and spoon any resting juices back over.",
    ],
    tip: "Always slice steak against the grain; it shortens the muscle fibres so each bite is far more tender.",
  },
  {
    title: "Shrimp and quinoa harvest bowl",
    by: "Dr. Priya Nair", byRole: "Dietician", diet: "Seafood",
    time: "20 min", servings: 1, kcal: 560, macros: { p: 40, c: 62, f: 16 },
    tags: ["Pescatarian", "Meal prep", "GF"],
    hero: "linear-gradient(135deg, #f1a48f 0%, #e07856 55%, #1a1612 100%)",
    blurb: "Friday — light enough for an evening session.",
    ingredients: [
      { n: "6 oz", m: "shrimp, peeled", k: "170 kcal" },
      { n: "3/4 cup", m: "cooked quinoa", k: "165 kcal" },
      { n: "1 cup", m: "roasted zucchini and peppers" },
      { n: "1 tbsp", m: "olive oil" },
      { n: "1/2", m: "lemon, juiced" },
      { n: "2 tbsp", m: "feta crumbles" },
      { n: "handful", m: "parsley, torn" },
    ],
    steps: [
      "Pat the shrimp very dry and season with salt and pepper — wet shrimp steam and turn rubbery instead of searing.",
      "Heat the olive oil in a skillet over medium-high until it shimmers and just starts to ripple.",
      "Add the shrimp in a single layer and cook 2 minutes per side, just until they curl into a loose C-shape and turn opaque. A tight O means overcooked.",
      "Squeeze the lemon over the pan to deglaze, swirling the shrimp in the juices for 15 seconds.",
      "Build the bowl: warm quinoa as the base, roasted veg alongside, shrimp on top.",
      "Scatter with feta and torn parsley, and spoon the pan juices over for brightness.",
    ],
    tip: "Cook to colour, not the clock: shrimp are done the moment they're pink and opaque — they keep cooking off the heat. Prepped bowls keep 2 days chilled; add feta on the day.",
  },
  {
    title: "Black bean and sweet potato tacos",
    by: "Aisha Bello", byRole: "Nutritionist", diet: "Vegan",
    time: "20 min", servings: 1, kcal: 540, macros: { p: 24, c: 78, f: 14 },
    tags: ["Vegan", "Fiber", "Quick"],
    hero: "linear-gradient(135deg, #d8a64a 0%, #8b5e30 60%, #1a1612 100%)",
    blurb: "Saturday — easy and carby for a rest day.",
    ingredients: [
      { n: "1 cup", m: "black beans, cooked", k: "220 kcal" },
      { n: "1 small", m: "sweet potato, cubed", k: "100 kcal" },
      { n: "3", m: "corn tortillas", k: "150 kcal" },
      { n: "1/2", m: "avocado" },
      { n: "1", m: "lime" },
      { n: "handful", m: "cilantro" },
      { n: "to taste", m: "hot sauce" },
      { n: "1 tsp", m: "ground cumin" },
    ],
    steps: [
      "Heat the oven to 425°F (220°C). Toss the sweet potato cubes with a little oil, salt and half the cumin and roast 18 minutes until caramelised at the edges.",
      "Meanwhile, warm the black beans with the rest of the cumin and a splash of water; mash about a third of them so the mix clings to the tortilla.",
      "Char the corn tortillas over a gas flame or in a dry skillet, 20 seconds a side, until blistered and pliable.",
      "Mash the avocado with a squeeze of lime and a pinch of salt until spreadable but still chunky.",
      "Build each taco: a swipe of avocado first, then beans, then roasted sweet potato.",
      "Finish with torn cilantro, a squeeze of lime and a few dashes of hot sauce.",
    ],
    tip: "Mashing a portion of the beans is the trick to taco filling that holds together instead of rolling off.",
  },
  {
    title: "Red lentil and spinach dahl",
    by: "James Cole", byRole: "Dietician", diet: "Vegan",
    time: "30 min", servings: 2, kcal: 470, macros: { p: 24, c: 68, f: 12 },
    tags: ["Vegan", "Fiber", "Batch"],
    hero: "linear-gradient(135deg, #e0913c 0%, #a34e1f 60%, #1a1612 100%)",
    blurb: "A cheap, high-fibre staple that reheats beautifully.",
    ingredients: [
      { n: "1 cup", m: "red lentils", k: "460 kcal" },
      { n: "2 cups", m: "vegetable broth" },
      { n: "1 can", m: "chopped tomatoes" },
      { n: "2 cups", m: "spinach" },
      { n: "1", m: "onion, diced" },
      { n: "3 cloves", m: "garlic, minced" },
      { n: "1 tsp", m: "fresh ginger, minced" },
      { n: "1 tbsp", m: "curry powder" },
      { n: "1 tsp", m: "ground cumin" },
    ],
    steps: [
      "Rinse the red lentils under cold water until it runs clear — this removes surface starch so the dahl isn't gluey.",
      "Warm 1 tbsp oil in a pot over medium heat and soften the diced onion for 4 minutes, then add the minced garlic and ginger for another minute.",
      "Add the curry powder and cumin and toast for 30 seconds, stirring, until fragrant — blooming the spices deepens the flavour.",
      "Tip in the lentils, chopped tomatoes and broth, stir well, and bring the pot up to a boil.",
      "Lower to a simmer and cook 18–20 minutes, stirring now and then, until the lentils collapse into a creamy purée.",
      "Stir the spinach through in handfuls until wilted, season, and loosen with water if needed. Serve over rice.",
    ],
    tip: "Toast the spices in oil before the liquid goes in — the biggest upgrade for any curry. Keeps 4 days chilled and freezes for a month; it thickens overnight, so loosen with water on reheat.",
  },
  {
    title: "Chickpea shakshuka",
    by: "Rae Lindqvist", byRole: "Nutritionist", diet: "Vegetarian",
    time: "25 min", servings: 2, kcal: 430, macros: { p: 22, c: 46, f: 18 },
    tags: ["Vegetarian", "Brunch", "One-pan"],
    hero: "linear-gradient(135deg, #d9543b 0%, #e98a2e 55%, #1a1612 100%)",
    blurb: "Eggs and chickpeas make this a protein-forward brunch.",
    ingredients: [
      { n: "1 can", m: "chickpeas, drained", k: "360 kcal" },
      { n: "1 can", m: "chopped tomatoes" },
      { n: "4", m: "eggs", k: "280 kcal" },
      { n: "1", m: "onion, diced" },
      { n: "1", m: "red pepper, diced" },
      { n: "1 tsp", m: "smoked paprika" },
      { n: "1/2 tsp", m: "ground cumin" },
      { n: "2 tbsp", m: "feta, crumbled" },
      { n: "handful", m: "parsley" },
    ],
    steps: [
      "Warm 1 tbsp oil in an oven-safe skillet over medium and soften the diced onion and red pepper for 6 minutes until slumped and sweet.",
      "Stir in the smoked paprika and cumin and cook 30 seconds to bloom the spices in the hot oil.",
      "Add the chopped tomatoes and drained chickpeas, season, and simmer 8 minutes until the sauce holds a spoon-trail.",
      "Make four wells in the sauce with the back of a spoon and crack an egg into each one.",
      "Cover and cook 5–6 minutes, until the whites are set but the yolks still wobble — or slide under a hot grill for runnier yolks.",
      "Scatter with crumbled feta and parsley and serve with bread for dipping.",
    ],
    tip: "Stop cooking while the yolks still jiggle; they keep setting in the hot sauce on the way to the table.",
  },
  {
    title: "Miso-glazed cod with greens",
    by: "Marco Bellini", byRole: "Nutritionist", diet: "Seafood",
    time: "20 min", servings: 1, kcal: 410, macros: { p: 42, c: 18, f: 16 },
    tags: ["Seafood", "Low carb"],
    hero: "linear-gradient(135deg, #6fae8e 0%, #2f6d5b 55%, #1a1612 100%)",
    blurb: "A restaurant move that takes ten minutes at home.",
    ingredients: [
      { n: "6 oz", m: "cod fillet", k: "140 kcal" },
      { n: "1 tbsp", m: "white miso" },
      { n: "1 tsp", m: "honey" },
      { n: "1 tsp", m: "soy sauce" },
      { n: "1 tsp", m: "mirin" },
      { n: "2 cups", m: "bok choy, halved" },
      { n: "1 tsp", m: "sesame seeds" },
      { n: "1", m: "spring onion, sliced" },
    ],
    steps: [
      "Heat the grill (broiler) to high and line a tray with foil so the sticky glaze can't weld to the pan.",
      "Whisk the miso, honey, soy and mirin into a smooth, glossy glaze — no lumps, it should ribbon off the whisk.",
      "Pat the cod dry, set it on the tray, and brush a thick layer of glaze over the top.",
      "Grill 8–10 minutes, watching closely, until the glaze caramelises to a lacquered amber and the fish flakes at a gentle press. If it darkens too fast, drop the shelf a level.",
      "While it cooks, halve the bok choy and steam or stir-fry it 3 minutes until the stems are crisp-tender.",
      "Plate the cod on the greens and finish with sesame seeds and sliced spring onion.",
    ],
    tip: "Miso burns quickly because of its sugars — keep the fish a few inches from the element and stay by the oven.",
  },
  {
    title: "Tofu and edamame poke bowl",
    by: "Aisha Bello", byRole: "Nutritionist", diet: "Plant-based",
    time: "15 min", prep: "10 min press", servings: 1, kcal: 520, macros: { p: 26, c: 64, f: 18 },
    tags: ["Plant-based", "No-cook", "Bowl"],
    hero: "linear-gradient(135deg, #5fbf8f 0%, #3a8f6a 50%, #1a1612 100%)",
    blurb: "Crispy tofu, cool rice, all the toppings.",
    ingredients: [
      { n: "6 oz", m: "firm tofu, cubed", k: "150 kcal" },
      { n: "3/4 cup", m: "sushi rice, cooked", k: "180 kcal" },
      { n: "1/2 cup", m: "edamame, shelled" },
      { n: "1/2", m: "cucumber, sliced" },
      { n: "1", m: "carrot, ribboned" },
      { n: "1/2", m: "avocado" },
      { n: "1 tbsp", m: "soy sauce" },
      { n: "1 tbsp", m: "sriracha mayo" },
    ],
    steps: [
      "Press the tofu: wrap the block in a clean towel and rest a heavy pan on top for 10 minutes to squeeze out water so it crisps instead of steaming.",
      "Cube the tofu and pan-fry in 1 tsp oil over medium-high, 6–8 minutes, turning so several sides turn golden and firm.",
      "Toss the hot tofu in a splash of soy off the heat so it drinks the seasoning in while it's porous.",
      "Spoon the cooled sushi rice into a bowl as the base and season it with a pinch of salt.",
      "Arrange the edamame, sliced cucumber, ribboned carrot and avocado in sections around the rice.",
      "Add the tofu and finish with a drizzle of sriracha mayo just before eating.",
    ],
    tip: "Pressing tofu is non-negotiable for crispiness — the drier the block, the better the crust.",
  },
  {
    title: "Grilled chicken Caesar, lightened",
    by: "Tom Okafor", byRole: "Nutritionist", diet: "Poultry",
    time: "20 min", servings: 1, kcal: 500, macros: { p: 50, c: 22, f: 22 },
    tags: ["High protein", "Low carb"],
    hero: "linear-gradient(135deg, #cdb98a 0%, #7e6a3c 55%, #1a1612 100%)",
    blurb: "A yogurt-based dressing keeps it lean without losing the punch.",
    ingredients: [
      { n: "6 oz", m: "chicken breast", k: "280 kcal" },
      { n: "1 head", m: "romaine, chopped" },
      { n: "2 tbsp", m: "Greek yogurt" },
      { n: "1/2", m: "lemon, juiced" },
      { n: "1 clove", m: "garlic, grated" },
      { n: "1 tbsp", m: "parmesan, grated" },
      { n: "1/4 tsp", m: "anchovy paste" },
      { n: "handful", m: "wholegrain croutons" },
    ],
    steps: [
      "Butterfly or pound the chicken breast to an even thickness so it cooks through without drying out, then season both sides.",
      "Grill or pan-sear over medium-high, 5 minutes per side, until the internal temp hits 165°F with clear grill marks.",
      "Rest the chicken 5 minutes while you make the dressing so the juices settle back in.",
      "Whisk the Greek yogurt with lemon, grated garlic, parmesan and a tiny dab of anchovy paste — the anchovy adds savoury depth without fishiness.",
      "Toss the chopped romaine with just enough dressing to coat lightly — the leaves should glisten, not drip.",
      "Slice the chicken, lay it over the salad, and finish with croutons and extra parmesan.",
    ],
    tip: "Pound the breast to an even thickness — thin tips overcook before thick centres are done, and evenness is the whole game.",
  },
  {
    title: "Beef and broccoli stir-fry",
    by: "Daniel Reyes", byRole: "Dietician", diet: "Meat",
    time: "20 min", prep: "10 min marinade", servings: 1, kcal: 600, macros: { p: 45, c: 48, f: 24 },
    tags: ["High protein", "Wok"],
    hero: "linear-gradient(135deg, #7a3320 0%, #b8552f 55%, #1a1612 100%)",
    blurb: "Hot pan, fast hands — better than takeout.",
    ingredients: [
      { n: "6 oz", m: "flank steak, sliced thin", k: "300 kcal" },
      { n: "3 cups", m: "broccoli florets" },
      { n: "2 tbsp", m: "soy sauce" },
      { n: "1 tbsp", m: "oyster sauce" },
      { n: "2 cloves", m: "garlic, minced" },
      { n: "1 tsp", m: "fresh ginger, minced" },
      { n: "1 tsp", m: "cornstarch" },
      { n: "3/4 cup", m: "rice, to serve", k: "160 kcal" },
    ],
    steps: [
      "Slice the flank steak as thin as you can across the grain and toss with 1 tsp soy and the cornstarch; rest 10 minutes to tenderise.",
      "Mix the remaining soy, the oyster sauce and 2 tbsp water so the sauce is ready before the pan gets hot.",
      "Get a wok or large skillet smoking hot with 1 tbsp oil. Sear the beef in a single layer 90 seconds without moving it, then flip and remove — it should still be a touch underdone.",
      "Add the broccoli with a splash of water, cover, and steam-fry 3 minutes, until it turns bright green and the water has cooked away.",
      "Uncover, add the garlic and ginger, and toss 30 seconds — just until fragrant, before the garlic can colour and turn bitter.",
      "Return the beef, pour in the sauce, and toss 1 minute until it thickens and glosses everything.",
      "Serve immediately over rice while the broccoli still has snap.",
    ],
    tip: "Cook the beef and broccoli separately and combine at the end — crowding the pan drops the heat and you'll braise, not stir-fry.",
  },
  {
    title: "Tempeh and broccoli teriyaki",
    by: "Elena Voss", byRole: "Dietician", diet: "Vegan",
    time: "25 min", servings: 1, kcal: 540, macros: { p: 32, c: 58, f: 18 },
    tags: ["Vegan", "High protein", "Meal prep"],
    hero: "linear-gradient(135deg, #b89a3c 0%, #6b6a23 55%, #1a1612 100%)",
    blurb: "Tempeh brings the protein vegans often miss at dinner.",
    ingredients: [
      { n: "6 oz", m: "tempeh, sliced", k: "330 kcal" },
      { n: "3 cups", m: "broccoli florets" },
      { n: "3 tbsp", m: "teriyaki sauce" },
      { n: "2 cloves", m: "garlic, minced" },
      { n: "1 tsp", m: "fresh ginger, minced" },
      { n: "3/4 cup", m: "brown rice, cooked", k: "160 kcal" },
      { n: "1 tsp", m: "sesame seeds" },
    ],
    steps: [
      "Slice the tempeh into thin planks and steam them 5 minutes — this mellows the slightly bitter edge and helps it absorb the glaze.",
      "Pat the planks dry, then pan-fry in 1 tsp oil over medium-high, 3 minutes a side, until golden and crisp.",
      "Add the broccoli and a splash of water, cover, and steam-fry 4 minutes until crisp-tender.",
      "Add the garlic and ginger and stir 30 seconds, until fragrant but not coloured.",
      "Pour in the teriyaki and toss 2 minutes, until it reduces and clings to everything as a sticky glaze.",
      "Spoon over warm brown rice and finish with a scatter of sesame seeds.",
    ],
    tip: "Steam tempeh before frying if you've found it bitter before — it opens up to soak in the sauce. Boxes keep 3 days chilled; the glaze revives with a splash of water on reheat.",
  },
  {
    title: "Tuna niçoise bowl",
    by: "Dr. Priya Nair", byRole: "Dietician", diet: "Seafood",
    time: "15 min", servings: 1, kcal: 480, macros: { p: 38, c: 34, f: 22 },
    tags: ["Seafood", "No-cook", "Omega-3"],
    hero: "linear-gradient(135deg, #4f8fb0 0%, #2c5a74 55%, #1a1612 100%)",
    blurb: "Pantry tuna, fresh veg — done in the time it takes to boil eggs.",
    ingredients: [
      { n: "1 can", m: "tuna in water", k: "120 kcal" },
      { n: "2", m: "eggs", k: "140 kcal" },
      { n: "5", m: "baby potatoes, halved" },
      { n: "1 cup", m: "green beans, trimmed" },
      { n: "6", m: "cherry tomatoes, halved" },
      { n: "8", m: "olives" },
      { n: "1 tbsp", m: "olive oil" },
      { n: "1 tsp", m: "dijon mustard" },
    ],
    steps: [
      "Bring a pot of water to a gentle boil and lower in the eggs for exactly 7 minutes for jammy yolks, then chill in cold water and peel.",
      "In the same water, boil the halved baby potatoes 8 minutes — they will still be firm at this point, which is what you want.",
      "Drop the green beans in for the last 2 minutes, until they are bright and still squeak and a knife slides into the thickest potato with no resistance, then drain everything together.",
      "Whisk the vinaigrette: olive oil, dijon, a squeeze of lemon, salt and pepper, until slightly thickened.",
      "Drain the tuna well and break it into large flakes rather than mashing it fine.",
      "Arrange the potatoes, beans, halved tomatoes, olives and tuna in sections in a bowl, and halve the eggs on top.",
      "Spoon the vinaigrette over everything just before serving so nothing sits soggy.",
    ],
    tip: "Boil eggs and potatoes in the same pot to save time and washing-up — start the eggs, add potatoes alongside.",
  },
  {
    title: "Roasted veg and halloumi traybake",
    by: "Marco Bellini", byRole: "Nutritionist", diet: "Vegetarian",
    time: "35 min", servings: 2, kcal: 520, macros: { p: 26, c: 44, f: 28 },
    tags: ["Vegetarian", "Sheet-pan"],
    hero: "linear-gradient(135deg, #c98a4e 0%, #7e5a2c 55%, #1a1612 100%)",
    blurb: "Halloumi gets golden and squeaky — no fussing required.",
    ingredients: [
      { n: "7 oz", m: "halloumi, sliced", k: "620 kcal" },
      { n: "1", m: "courgette, chunked" },
      { n: "1", m: "red pepper, chunked" },
      { n: "1", m: "red onion, wedged" },
      { n: "1 can", m: "chickpeas, drained", k: "360 kcal" },
      { n: "2 tbsp", m: "olive oil" },
      { n: "1 tsp", m: "dried oregano" },
      { n: "1 tsp", m: "paprika" },
      { n: "1/2", m: "lemon" },
    ],
    steps: [
      "Heat the oven to 425°F (220°C) with a rack in the top third so the veg colours instead of stewing.",
      "Chop the courgette, pepper and red onion into similar chunks, drain and dry the chickpeas, and toss everything with the oil, oregano, paprika, salt and pepper.",
      "Spread in a single layer — crowding steams the veg — and roast 20 minutes until starting to colour.",
      "Pat the halloumi slices dry, nestle them among the veg, and roast a further 10 minutes until the cheese is golden and the veg edges char.",
      "Squeeze lemon over the hot tray to cut the richness and serve straight away, while the halloumi is still soft.",
    ],
    tip: "Halloumi turns rubbery as it cools — serve it the moment it comes out of the oven for that squeaky bite.",
  },
  {
    title: "Quinoa rainbow Buddha bowl",
    by: "Mara Whitfield", byRole: "Dietician", diet: "Plant-based",
    time: "25 min", servings: 1, kcal: 560, macros: { p: 22, c: 72, f: 20 },
    tags: ["Plant-based", "Fiber", "Bowl"],
    hero: "linear-gradient(135deg, #6fae5a 0%, #b89a3c 55%, #1a1612 100%)",
    blurb: "Every colour on the plate — and a tahini drizzle to tie it together.",
    ingredients: [
      { n: "3/4 cup", m: "cooked quinoa", k: "165 kcal" },
      { n: "1 small", m: "sweet potato, cubed" },
      { n: "1/2 can", m: "chickpeas, drained", k: "180 kcal" },
      { n: "1 cup", m: "red cabbage, sliced" },
      { n: "1", m: "carrot, ribboned" },
      { n: "1/2", m: "avocado, sliced" },
      { n: "2 tbsp", m: "tahini" },
      { n: "1/2", m: "lemon, juiced" },
      { n: "1 tbsp", m: "pumpkin seeds" },
    ],
    steps: [
      "Heat the oven to 425°F (220°C). Toss the cubed sweet potato and drained chickpeas with oil and salt and roast 20 minutes, shaking halfway, until tender and crisp.",
      "While that roasts, cook the quinoa if needed, and thinly slice the red cabbage and ribbon the carrot.",
      "Make the dressing: whisk the tahini with lemon juice and a pinch of salt — it'll seize and thicken first, then loosen with water a teaspoon at a time until it pours.",
      "Spoon the quinoa into a bowl and arrange the roasted and raw veg in colour-blocked sections.",
      "Add sliced avocado, drizzle generously with the tahini dressing, and scatter with pumpkin seeds.",
    ],
    tip: "Tahini dressing always seizes before it smooths — keep adding water a little at a time and it comes together silky.",
  },
  {
    title: "Turkey meatballs in marinara",
    by: "Daniel Reyes", byRole: "Dietician", diet: "Poultry",
    time: "30 min", servings: 2, kcal: 580, macros: { p: 44, c: 52, f: 20 },
    tags: ["High protein", "Family"],
    hero: "linear-gradient(135deg, #c0432f 0%, #832a1c 55%, #1a1612 100%)",
    blurb: "Lean turkey, a quick marinara, over pasta or zoodles.",
    ingredients: [
      { n: "10 oz", m: "ground turkey", k: "440 kcal" },
      { n: "1", m: "egg" },
      { n: "1/4 cup", m: "breadcrumbs" },
      { n: "2 cloves", m: "garlic, grated" },
      { n: "2 tbsp", m: "parmesan, grated" },
      { n: "handful", m: "parsley, chopped" },
      { n: "1 jar", m: "marinara sauce" },
      { n: "5 oz", m: "wholewheat pasta", k: "500 kcal" },
      { n: "handful", m: "basil" },
    ],
    steps: [
      "Combine the turkey, egg, breadcrumbs, grated garlic, parmesan, parsley, salt and pepper and mix with a light hand — overworking makes dense, tough meatballs.",
      "Roll into golf-ball sized rounds with damp hands so the mix doesn't stick to your palms.",
      "Brown them in a little oil over medium-high, turning, about 6 minutes — colour, not cooked through yet.",
      "Pour in the marinara, scraping up the fond, bring to a simmer, and cook gently 12 minutes until the meatballs hit 165°F and the sauce thickens.",
      "Meanwhile, boil the pasta in well-salted water to al dente and reserve a splash of the cooking water.",
      "Toss the pasta with a little sauce (loosen with pasta water), top with meatballs and sauce, and tear basil over.",
    ],
    tip: "Mix the meatball mixture just until combined — the gentler you are, the more tender they stay. Meatballs in sauce keep 3 days chilled and freeze beautifully.",
  },
  {
    title: "Smoked salmon and avocado toast",
    by: "Rae Lindqvist", byRole: "Nutritionist", diet: "Seafood",
    time: "10 min", servings: 1, kcal: 440, macros: { p: 28, c: 38, f: 20 },
    tags: ["Seafood", "Breakfast", "Omega-3"],
    hero: "linear-gradient(135deg, #e6917a 0%, #b65a48 55%, #1a1612 100%)",
    blurb: "Five minutes, restaurant brunch energy.",
    ingredients: [
      { n: "2 slices", m: "rye or sourdough", k: "180 kcal" },
      { n: "1/2", m: "avocado" },
      { n: "3 oz", m: "smoked salmon", k: "100 kcal" },
      { n: "1/2", m: "lemon" },
      { n: "1 tsp", m: "capers" },
      { n: "2 sprigs", m: "fresh dill" },
      { n: "to taste", m: "cracked black pepper" },
    ],
    steps: [
      "Toast the rye or sourdough 3–4 minutes until deeply golden and crisp — a sturdy base stops it going soggy under the toppings.",
      "Mash the avocado with a squeeze of lemon and a pinch of salt, then spread it thickly all the way to the edges.",
      "Drape the smoked salmon over in loose folds rather than flat — the ruffles look and eat better.",
      "Scatter with capers, fresh dill and plenty of cracked black pepper.",
      "For something heartier, slide a poached egg on top and break the yolk just before serving with a final squeeze of lemon.",
    ],
    tip: "For a clean poached egg, use the freshest egg you can and swirl the simmering water into a gentle vortex before dropping it in.",
  },
  {
    title: "Black-eyed pea and coconut curry",
    by: "James Cole", byRole: "Dietician", diet: "Vegan",
    time: "30 min", servings: 2, kcal: 500, macros: { p: 20, c: 66, f: 16 },
    tags: ["Vegan", "Fiber", "Batch"],
    hero: "linear-gradient(135deg, #cf8a3a 0%, #6f8a3c 55%, #1a1612 100%)",
    blurb: "Creamy, warming, and full of plant protein and fibre.",
    ingredients: [
      { n: "1 can", m: "black-eyed peas, drained", k: "320 kcal" },
      { n: "1 can", m: "light coconut milk", k: "240 kcal" },
      { n: "1 can", m: "chopped tomatoes" },
      { n: "1", m: "onion, diced" },
      { n: "3 cloves", m: "garlic, minced" },
      { n: "1 tsp", m: "fresh ginger, minced" },
      { n: "1 tbsp", m: "curry powder" },
      { n: "1/2 tsp", m: "turmeric" },
      { n: "2 cups", m: "spinach" },
      { n: "1", m: "lime" },
    ],
    steps: [
      "Soften the diced onion in 1 tbsp oil over medium heat for 4 minutes, then add the minced garlic and ginger for another minute.",
      "Stir in the curry powder and turmeric and toast 30 seconds until fragrant — bloom them in the oil, not the liquid.",
      "Add the tomatoes and let them cook down 3 minutes until jammy and starting to split.",
      "Pour in the coconut milk and drained black-eyed peas, bring to a gentle simmer, and cook 15 minutes until thickened and glossy.",
      "Wilt the spinach through at the end, finish with a squeeze of lime and salt to taste, and serve over rice.",
    ],
    tip: "A squeeze of lime at the very end lifts a coconut curry — the acidity balances the richness. Keeps 4 days chilled; the flavour is even better on day two.",
  },
  {
    title: "Cauliflower steak, chimichurri",
    by: "Aisha Bello", byRole: "Nutritionist", diet: "Plant-based",
    time: "30 min", servings: 2, kcal: 380, macros: { p: 12, c: 34, f: 22 },
    tags: ["Plant-based", "Low cal", "GF"],
    hero: "linear-gradient(135deg, #9abf6a 0%, #4f6d2c 55%, #1a1612 100%)",
    blurb: "A meatless centrepiece with real char and a punchy sauce.",
    ingredients: [
      { n: "1 large", m: "cauliflower" },
      { n: "2 tbsp", m: "olive oil", k: "240 kcal" },
      { n: "1 tsp", m: "smoked paprika" },
      { n: "1/2 tsp", m: "ground cumin" },
      { n: "1 cup", m: "parsley and cilantro, chopped" },
      { n: "2 cloves", m: "garlic, minced" },
      { n: "2 tbsp", m: "red wine vinegar" },
      { n: "pinch", m: "chili flakes" },
    ],
    steps: [
      "Heat the oven to 440°F (225°C). Trim the cauliflower and slice it through the core into two or three thick 1-inch 'steaks' — keeping the core attached holds each slab together.",
      "Brush both sides with olive oil and rub with the smoked paprika, cumin, salt and pepper.",
      "Roast 25 minutes, flipping carefully halfway, until the edges are deeply charred and a knife slides through the stem.",
      "Meanwhile, finely chop the parsley and cilantro and stir together with minced garlic, red wine vinegar, chili flakes, the remaining olive oil and a pinch of salt to make the chimichurri.",
      "Let the chimichurri sit 10 minutes so the flavours meld before it meets the heat.",
      "Spoon it generously over the hot cauliflower steaks just before serving.",
    ],
    tip: "Slice through the core, not across it — the stem is the spine that keeps a cauliflower steak in one piece on the flip.",
  },
  {
    title: "Chicken pesto pasta",
    by: "Tom Okafor", byRole: "Nutritionist", diet: "Poultry",
    time: "25 min", servings: 1, kcal: 640, macros: { p: 46, c: 66, f: 22 },
    tags: ["High protein", "Quick", "Family"],
    hero: "linear-gradient(135deg, #8fb36a 0%, #4f6d2c 55%, #1a1612 100%)",
    blurb: "Weeknight staple — fast, high-protein, and kid-friendly.",
    ingredients: [
      { n: "6 oz", m: "chicken breast", k: "280 kcal" },
      { n: "3 oz", m: "penne or fusilli", k: "300 kcal" },
      { n: "2 tbsp", m: "basil pesto", k: "160 kcal" },
      { n: "8", m: "cherry tomatoes, halved" },
      { n: "1 tbsp", m: "parmesan, grated" },
      { n: "1 tbsp", m: "olive oil" },
      { n: "pinch", m: "salt and pepper" },
    ],
    steps: [
      "Bring a large pot of well-salted water to a boil and cook the pasta to al dente; reserve a mug of the starchy cooking water before draining.",
      "Meanwhile, season the chicken and pan-sear in a little olive oil over medium-high, 5 minutes per side, until it hits 165°F; rest, then slice.",
      "Off the heat, toss the drained pasta with the pesto, loosening with a splash of pasta water until it coats every piece.",
      "Fold through the halved cherry tomatoes and the sliced chicken.",
      "Finish with the parmesan and a good crack of black pepper over the top.",
    ],
    tip: "Always save a little pasta water — its starch is what turns pesto into a sauce that clings instead of sliding off.",
  },
  {
    title: "Garlic shrimp linguine",
    by: "Marco Bellini", byRole: "Nutritionist", diet: "Seafood",
    time: "20 min", servings: 1, kcal: 580, macros: { p: 34, c: 64, f: 18 },
    tags: ["Seafood", "Quick"],
    hero: "linear-gradient(135deg, #e6a06a 0%, #b05a3c 55%, #1a1612 100%)",
    blurb: "Restaurant scampi, ready before the pasta water's even cooled.",
    ingredients: [
      { n: "6 oz", m: "shrimp, peeled", k: "170 kcal" },
      { n: "3 oz", m: "linguine", k: "300 kcal" },
      { n: "3 cloves", m: "garlic, sliced" },
      { n: "splash", m: "white wine" },
      { n: "1/2", m: "lemon" },
      { n: "pinch", m: "chili flakes" },
      { n: "handful", m: "parsley, chopped" },
      { n: "2 tbsp", m: "olive oil", k: "240 kcal" },
    ],
    steps: [
      "Cook the linguine in well-salted boiling water to al dente; reserve some pasta water before draining.",
      "While it boils, pat the shrimp dry and season with salt so they sear rather than steam.",
      "Warm the olive oil over medium, add the sliced garlic and chili flakes, and cook about 1 minute until fragrant but not browned — burnt garlic turns bitter.",
      "Add the shrimp and cook 2 minutes, turning once, until they curl and turn opaque right through.",
      "Pour in the wine with a squeeze of lemon and let it bubble 1 minute, until the sharpness cooks off and the sauce thickens slightly.",
      "Toss the linguine into the pan with a splash of pasta water, swirling until the sauce turns glossy and coats the strands.",
      "Finish with the chopped parsley, another squeeze of lemon, and a thread of olive oil off the heat.",
    ],
    tip: "Pull the garlic off the heat the moment it's pale gold — bitter, over-browned garlic is the most common way this dish goes wrong.",
  },
  {
    title: "Lentil bolognese",
    by: "James Cole", byRole: "Dietician", diet: "Vegan",
    time: "35 min", servings: 2, kcal: 520, macros: { p: 22, c: 84, f: 10 },
    tags: ["Vegan", "Fiber", "Batch"],
    hero: "linear-gradient(135deg, #b5532f 0%, #6f2f1c 55%, #1a1612 100%)",
    blurb: "A hearty, high-fibre ragù that nobody misses the meat in.",
    ingredients: [
      { n: "1 cup", m: "cooked brown or green lentils", k: "230 kcal" },
      { n: "4 oz", m: "spaghetti", k: "400 kcal" },
      { n: "1 can", m: "chopped tomatoes" },
      { n: "1", m: "onion, finely diced" },
      { n: "1", m: "carrot, finely diced" },
      { n: "1 stick", m: "celery, finely diced" },
      { n: "2 cloves", m: "garlic, minced" },
      { n: "1 tbsp", m: "tomato paste" },
      { n: "1 tsp", m: "dried oregano" },
      { n: "1 tbsp", m: "olive oil" },
    ],
    steps: [
      "Finely dice the onion, carrot and celery and soften them in olive oil over medium heat for 8 minutes — this slow soffritto is the flavour base.",
      "Stir in the garlic, tomato paste and oregano and cook for 1 minute until the paste darkens a shade.",
      "Add the cooked lentils and chopped tomatoes, season, and simmer 15 minutes until thick and rich, adding a splash of water if it tightens.",
      "Meanwhile, cook the spaghetti in well-salted water to al dente; reserve some pasta water.",
      "Toss the pasta through the sauce with a splash of pasta water so it clings to every strand.",
      "Serve with a drizzle of olive oil (and a little vegan parmesan if you like).",
    ],
    tip: "Don't rush the soffritto — eight slow minutes on the onion, carrot and celery is what gives a meatless ragù its depth. The sauce keeps 4 days chilled and freezes for a month.",
  },
  {
    title: "Creamy tomato and white bean pasta",
    by: "Mara Whitfield", byRole: "Dietician", diet: "Vegetarian",
    time: "25 min", servings: 2, kcal: 560, macros: { p: 22, c: 82, f: 14 },
    tags: ["Vegetarian", "Fiber", "Comfort"],
    hero: "linear-gradient(135deg, #e08a5a 0%, #9a4a3a 55%, #1a1612 100%)",
    blurb: "Creamy without the cream — the white beans do the work.",
    ingredients: [
      { n: "1 can", m: "cannellini beans, drained", k: "330 kcal" },
      { n: "4 oz", m: "rigatoni", k: "400 kcal" },
      { n: "1 can", m: "chopped tomatoes" },
      { n: "1", m: "onion, diced" },
      { n: "2 cloves", m: "garlic, minced" },
      { n: "1 tbsp", m: "parmesan, grated" },
      { n: "handful", m: "basil, torn" },
      { n: "1 tbsp", m: "olive oil" },
      { n: "pinch", m: "chili flakes" },
    ],
    steps: [
      "Soften the diced onion and garlic in olive oil over medium heat for 5 minutes until translucent and sweet.",
      "Add the tomatoes and a pinch of chili flakes and simmer 8 minutes until jammy.",
      "Blend half the cannellini beans with a splash of water and stir them in — they make the sauce creamy without any cream — then add the whole beans.",
      "Meanwhile cook the rigatoni to al dente in well-salted water; reserve some pasta water before draining.",
      "Toss the pasta through the sauce, loosening with pasta water, and stir in the parmesan.",
      "Finish with the torn basil and one more crack of pepper just before it hits the table.",
    ],
    tip: "Blended white beans are a dietitian's trick for a creamy pasta sauce that's higher in fibre and protein than cream.",
  },
  {
    title: "Beef ragu rigatoni",
    by: "Daniel Reyes", byRole: "Dietician", diet: "Meat",
    time: "40 min", servings: 2, kcal: 680, macros: { p: 42, c: 70, f: 24 },
    tags: ["High protein", "Family"],
    hero: "linear-gradient(135deg, #7a3320 0%, #4a1f14 55%, #1a1612 100%)",
    blurb: "A quick weeknight ragù with low-and-slow flavour.",
    ingredients: [
      { n: "8 oz", m: "lean ground beef", k: "460 kcal" },
      { n: "4 oz", m: "rigatoni", k: "400 kcal" },
      { n: "1 can", m: "chopped tomatoes" },
      { n: "1", m: "onion, diced" },
      { n: "1", m: "carrot, diced" },
      { n: "2 cloves", m: "garlic, minced" },
      { n: "splash", m: "red wine" },
      { n: "1 tbsp", m: "tomato paste" },
      { n: "1 tbsp", m: "parmesan, grated" },
      { n: "1 tbsp", m: "olive oil" },
    ],
    steps: [
      "Brown the ground beef in olive oil over medium-high, pressing it flat and leaving it to crust before breaking it up; lift it out with a slotted spoon.",
      "In the same pan, soften the diced onion, carrot and garlic for 6 minutes until sweet and beginning to colour.",
      "Stir in the tomato paste, cook 1 minute, then deglaze with a splash of red wine, scraping the base.",
      "Return the beef, add the tomatoes, season, and simmer gently 20 minutes until thick.",
      "Cook the rigatoni to al dente; reserve some pasta water and toss the pasta through the ragù with a splash to bind.",
      "Serve topped with the parmesan and a final drizzle of olive oil.",
    ],
    tip: "Let the mince form a brown crust before you stir it — that fond is where a quick ragù gets its slow-cooked taste. The ragù keeps 3 days chilled and freezes well.",
  },
  // ── Kitchen Card wave expansion (2026-07-08) — nine new recipes filling the
  //    vegan / seafood / snack / batch-cook gaps, written to the detail bar. ──
  {
    title: "Chickpea and spinach curry",
    by: "Mara Whitfield", byRole: "Dietician", diet: "Vegan",
    time: "30 min", servings: 4, kcal: 460, macros: { p: 22, c: 58, f: 14 },
    tags: ["Vegan", "Batch", "Freezer"],
    hero: "linear-gradient(135deg, #d99a3c 0%, #7e6a23 55%, #1a1612 100%)",
    blurb: "The Sunday batch that feeds half the week.",
    ingredients: [
      { n: "2 cans", m: "chickpeas, drained", k: "720 kcal" },
      { n: "1 can", m: "chopped tomatoes" },
      { n: "1 can", m: "light coconut milk", k: "240 kcal" },
      { n: "1 large", m: "onion, diced" },
      { n: "4 cloves", m: "garlic, minced" },
      { n: "1 tbsp", m: "fresh ginger, grated" },
      { n: "2 tbsp", m: "curry powder" },
      { n: "4 cups", m: "spinach" },
      { n: "1", m: "lemon, juiced" },
    ],
    steps: [
      "Warm 1 tbsp oil in your largest pot over medium heat and cook the diced onion 6 minutes, stirring now and then, until soft and golden at the edges.",
      "Add the garlic and ginger and stir 1 minute, until they smell sweet rather than raw.",
      "Stir the curry powder in for 30 seconds, moving it constantly so the spices toast in the oil without catching and turning bitter.",
      "Tip in the tomatoes and simmer 4 minutes until they darken and thicken to a jammy paste — that reduction is the backbone of the sauce.",
      "Add the chickpeas and coconut milk, bring to a gentle simmer, and cook 15 minutes uncovered until the sauce coats a spoon and the chickpeas have softened into it.",
      "Turn off the heat and fold the spinach through in two handfuls until just wilted and still bright green.",
      "Finish with the lemon juice and salt to taste — the curry should taste rich first, then bright.",
    ],
    tip: "Portion into four boxes while warm; it keeps 4 days chilled and freezes for a month. The sauce thickens overnight — loosen with a splash of water when you reheat.",
  },
  {
    title: "Crispy tofu grain bowl",
    by: "Tom Okafor", byRole: "Nutritionist", diet: "Vegan",
    time: "25 min", prep: "10 min press", servings: 1, kcal: 560, macros: { p: 30, c: 62, f: 20 },
    tags: ["Vegan", "High protein", "Bowl"],
    hero: "linear-gradient(135deg, #9a8f3c 0%, #4f6d4c 55%, #1a1612 100%)",
    blurb: "Cornstarch is the crackle — tofu that actually crunches.",
    ingredients: [
      { n: "7 oz", m: "extra-firm tofu, cubed", k: "170 kcal" },
      { n: "1 tbsp", m: "cornstarch" },
      { n: "3/4 cup", m: "cooked farro or brown rice", k: "170 kcal" },
      { n: "1 cup", m: "shredded kale" },
      { n: "1/2", m: "avocado, sliced" },
      { n: "1 tbsp", m: "soy sauce" },
      { n: "1 tbsp", m: "tahini" },
      { n: "1/2", m: "lemon, juiced" },
      { n: "1 tsp", m: "maple syrup" },
    ],
    steps: [
      "Press the tofu 10 minutes under a heavy pan, then cut into 3/4-inch cubes and toss with the cornstarch until every face is dusted — that starch coat is what fries into a shell.",
      "Heat 1 tbsp oil in a nonstick skillet over medium-high until shimmering, add the tofu with space between cubes, and fry 8 minutes, turning every 2, until deep golden and rattling-crisp on most sides.",
      "Off the heat, splash the soy over the hot tofu and toss 10 seconds — it hisses, absorbs, and seasons the crust without softening it.",
      "Massage the shredded kale with a pinch of salt and a squeeze of lemon for 30 seconds until it darkens and relaxes.",
      "Whisk the tahini, remaining lemon, maple and a tablespoon of water into a pourable dressing.",
      "Build the bowl: grains, kale, avocado, tofu on top, dressing zigzagged over everything.",
    ],
    tip: "Cornstarch, space in the pan, and patience between turns — break any of the three and the crust goes soft.",
  },
  {
    title: "Overnight oats, three ways",
    by: "Mara Whitfield", byRole: "Dietician", diet: "Vegetarian",
    time: "5 min", prep: "overnight chill", servings: 1, kcal: 480, macros: { p: 28, c: 58, f: 14 },
    tags: ["Breakfast", "No-cook", "Meal prep"],
    hero: "linear-gradient(135deg, #d9c28f 0%, #8f7a4a 55%, #1a1612 100%)",
    blurb: "Five minutes tonight, three breakfasts sorted.",
    ingredients: [
      { n: "1/2 cup", m: "rolled oats", k: "190 kcal" },
      { n: "1 scoop", m: "whey or plant protein", k: "120 kcal" },
      { n: "3/4 cup", m: "milk of choice" },
      { n: "2 tbsp", m: "Greek yogurt" },
      { n: "1 tbsp", m: "chia seeds" },
      { n: "1 tsp", m: "honey or maple" },
      { n: "1/2 cup", m: "berries, banana or peanut butter" },
    ],
    steps: [
      "Whisk the protein powder into the milk first until completely smooth — adding powder to assembled oats leaves pockets of dry dust.",
      "Stir in the oats, chia, yogurt and sweetener in a jar until every oat is submerged, then lid it and chill at least 4 hours or overnight.",
      "In the morning the mix should be thick enough to hold a spoon upright; loosen with a splash of milk if it set too firm.",
      "Top it one of three ways — berries for lightness, banana and cinnamon for a pre-session carb push, or a peanut-butter swirl on rest days.",
    ],
    tip: "Make three jars on Sunday night — they keep 3 days chilled and the chia only improves. Add crunchy toppings in the morning, never the night before.",
  },
  {
    title: "Harissa salmon with couscous",
    by: "Rae Lindqvist", byRole: "Nutritionist", diet: "Seafood",
    time: "20 min", servings: 1, kcal: 580, macros: { p: 40, c: 52, f: 22 },
    tags: ["Seafood", "Quick", "Spice"],
    hero: "linear-gradient(135deg, #d9603b 0%, #8f3a2e 55%, #1a1612 100%)",
    blurb: "One spoon of harissa does all the heavy lifting.",
    ingredients: [
      { n: "6 oz", m: "salmon fillet", k: "310 kcal" },
      { n: "1 tbsp", m: "harissa paste" },
      { n: "1 tsp", m: "honey" },
      { n: "1/2 cup", m: "couscous, dry", k: "310 kcal" },
      { n: "3/4 cup", m: "hot vegetable stock" },
      { n: "6", m: "cherry tomatoes, halved" },
      { n: "1/2", m: "cucumber, diced" },
      { n: "handful", m: "mint, torn" },
      { n: "1/2", m: "lemon" },
    ],
    steps: [
      "Heat the oven to 425°F (220°C). Stir the harissa and honey together and spread the paste over the top of the salmon like a thin plaster.",
      "Roast the salmon on a lined tray 10–12 minutes, until the glaze darkens at the edges and the flesh flakes at a gentle press but still looks silky inside.",
      "While it roasts, pour the hot stock over the couscous in a bowl, cover with a plate, and leave 5 minutes — then fork the grains apart so they don't clump.",
      "Fold the tomatoes, cucumber and most of the mint through the couscous with a squeeze of lemon and a little olive oil.",
      "Sit the salmon on the couscous, scatter the last of the mint over, and finish with the remaining lemon.",
    ],
    tip: "Harissa brands vary wildly in heat — taste yours first and cut it with extra honey if it bites harder than you like.",
  },
  {
    title: "Garlic shrimp and courgette noodles",
    by: "Tom Okafor", byRole: "Nutritionist", diet: "Seafood",
    time: "15 min", servings: 1, kcal: 370, macros: { p: 36, c: 14, f: 18 },
    tags: ["Seafood", "Low carb", "GF"],
    hero: "linear-gradient(135deg, #8fbf7a 0%, #3f7a5a 55%, #1a1612 100%)",
    blurb: "Scampi energy, a third of the carbs.",
    ingredients: [
      { n: "6 oz", m: "shrimp, peeled", k: "170 kcal" },
      { n: "2 medium", m: "courgettes, spiralised" },
      { n: "3 cloves", m: "garlic, sliced" },
      { n: "2 tbsp", m: "olive oil", k: "240 kcal" },
      { n: "pinch", m: "chili flakes" },
      { n: "1/2", m: "lemon" },
      { n: "handful", m: "parsley, chopped" },
      { n: "2 tbsp", m: "parmesan, grated" },
    ],
    steps: [
      "Spiralise the courgettes and salt them lightly in a colander for 10 minutes while you prep — then squeeze and pat them dry so they sauté instead of flooding the pan.",
      "Pat the shrimp dry, season, and sear in 1 tbsp oil over medium-high for 90 seconds a side until pink, opaque and curled to a loose C. Lift them out.",
      "Drop the heat to medium, add the rest of the oil with the garlic and chili flakes, and cook 1 minute until pale gold and fragrant — no browner.",
      "Add the courgette noodles and toss just 60–90 seconds, until barely tender but still with bite — past that they collapse into water.",
      "Return the shrimp with a big squeeze of lemon, toss once, and serve immediately with parsley and parmesan.",
    ],
    tip: "Salt, squeeze and dry the noodles — watery zoodles are the whole reason people give up on them.",
  },
  {
    title: "Cottage cheese protein toast",
    by: "Rae Lindqvist", byRole: "Nutritionist", diet: "Vegetarian",
    time: "5 min", servings: 1, kcal: 340, macros: { p: 28, c: 34, f: 10 },
    tags: ["Snack", "High protein", "No-cook"],
    hero: "linear-gradient(135deg, #e8d9b0 0%, #a68a4a 55%, #1a1612 100%)",
    blurb: "The between-sessions snack that actually holds you.",
    ingredients: [
      { n: "2 slices", m: "wholegrain or sourdough", k: "180 kcal" },
      { n: "3/4 cup", m: "cottage cheese", k: "120 kcal" },
      { n: "1 tsp", m: "olive oil or honey" },
      { n: "pinch", m: "flaky salt and pepper" },
      { n: "to taste", m: "chili flakes or cinnamon" },
      { n: "6", m: "cherry tomatoes, or 1/2 cup berries" },
    ],
    steps: [
      "Toast the bread until properly golden and rigid — cottage cheese is wet, and a pale slice will sag under it inside a minute.",
      "Spoon the cottage cheese thickly over both slices while the toast is still hot, so the underside just starts to warm.",
      "Go savoury (halved tomatoes, olive oil, flaky salt, chili flakes and pepper) or sweet (berries, honey and cinnamon) — both directions work over the same base.",
      "Eat straight away while the contrast holds: cold curds, warm crunch.",
    ],
    tip: "Whipped in a blender for 20 seconds, cottage cheese turns into a smooth spread even the sceptics eat.",
  },
  {
    title: "Date and almond energy bites",
    by: "Mara Whitfield", byRole: "Dietician", diet: "Plant-based",
    time: "15 min", prep: "30 min chill", servings: 4, kcal: 370, macros: { p: 10, c: 44, f: 16 },
    tags: ["Snack", "No-cook", "Batch"],
    hero: "linear-gradient(135deg, #8f6a3c 0%, #4f3a23 55%, #1a1612 100%)",
    blurb: "A dozen bites in the fridge beats any vending machine.",
    ingredients: [
      { n: "12", m: "Medjool dates, pitted", k: "800 kcal" },
      { n: "1 cup", m: "almonds", k: "550 kcal" },
      { n: "1/2 cup", m: "rolled oats" },
      { n: "2 tbsp", m: "cocoa powder" },
      { n: "1 tbsp", m: "chia seeds" },
      { n: "pinch", m: "flaky salt" },
      { n: "splash", m: "water, if needed" },
    ],
    steps: [
      "Pulse the almonds and oats in a food processor about 20 seconds, until they're a coarse rubble — stop before it turns to flour or the bites lose their bite.",
      "Add the pitted dates, cocoa, chia and salt and run 60–90 seconds, scraping down once, until the mix clumps and holds when you pinch it; add water a teaspoon at a time only if it stays crumbly.",
      "Roll into 12 walnut-sized balls with lightly damp hands, pressing firmly so they compact.",
      "Chill 30 minutes to set — they go from soft fudge to a clean, firm bite.",
    ],
    tip: "They keep 2 weeks in a sealed box in the fridge and a month in the freezer — three bites is one serving, which is easy to forget.",
  },
  {
    title: "Turkey chili verde",
    by: "Tom Okafor", byRole: "Nutritionist", diet: "Poultry",
    time: "35 min", servings: 4, kcal: 460, macros: { p: 42, c: 34, f: 16 },
    tags: ["High protein", "Batch", "Freezer"],
    hero: "linear-gradient(135deg, #7a9a3c 0%, #3f5a23 55%, #1a1612 100%)",
    blurb: "The green chili — lighter than red, twice as interesting.",
    ingredients: [
      { n: "1.25 lb", m: "lean ground turkey", k: "920 kcal" },
      { n: "1 jar", m: "salsa verde (16 oz)" },
      { n: "1 can", m: "white beans, drained", k: "330 kcal" },
      { n: "1", m: "onion, diced" },
      { n: "1", m: "green pepper, diced" },
      { n: "3 cloves", m: "garlic, minced" },
      { n: "2 tsp", m: "ground cumin" },
      { n: "1 tsp", m: "dried oregano" },
      { n: "1 cup", m: "chicken stock" },
      { n: "1", m: "lime, plus cilantro to serve" },
    ],
    steps: [
      "Brown the turkey in 1 tbsp oil over medium-high in a wide pot, pressing it into a flat layer and leaving it 3 minutes to crust before breaking it up — colour equals flavour in a lean chili.",
      "Add the onion and green pepper and cook 5 minutes, until softened and translucent at the edges.",
      "Stir in the garlic, cumin and oregano and give it 1 minute, until the whole pot smells toasty.",
      "Pour in the salsa verde, stock and beans, scraping the base clean, and bring to a simmer.",
      "Cook uncovered 20 minutes, stirring occasionally, until the chili thickens enough that a spoon dragged through leaves a trail.",
      "Finish with a big squeeze of lime, taste for salt, and serve with cilantro — and rice, or straight from the bowl.",
    ],
    tip: "Portion into four and it keeps 4 days chilled or 2 months frozen; the verde flavour deepens by day two. A spoon of Greek yogurt on top adds 5 g protein per bowl.",
  },
  {
    title: "Lemon-herb chicken meal-prep box",
    by: "Rae Lindqvist", byRole: "Nutritionist", diet: "Poultry",
    time: "35 min", prep: "10 min marinade", servings: 4, kcal: 510, macros: { p: 44, c: 48, f: 14 },
    tags: ["High protein", "Meal prep", "Batch"],
    hero: "linear-gradient(135deg, #d9c25a 0%, #8f7a2e 55%, #1a1612 100%)",
    blurb: "Four lunches, one tray, zero decisions on Wednesday.",
    ingredients: [
      { n: "1.5 lb", m: "chicken breast", k: "1000 kcal" },
      { n: "2", m: "lemons — zest and juice" },
      { n: "3 cloves", m: "garlic, minced" },
      { n: "1 tbsp", m: "dried oregano" },
      { n: "2 tbsp", m: "olive oil" },
      { n: "1 cup", m: "rice, dry", k: "680 kcal" },
      { n: "1 lb", m: "green beans, trimmed" },
      { n: "1/2 tsp", m: "salt, plus pepper" },
    ],
    steps: [
      "Whisk the lemon zest and juice, garlic, oregano, oil, salt and pepper; slice the chicken into even 1-inch strips and marinate 10 minutes while the oven heats to 425°F (220°C).",
      "Cook the rice: rinse, then simmer covered on low 15 minutes and rest 5 off the heat — no peeking, the steam does the finishing.",
      "Spread the chicken on one half of a lined sheet pan and the green beans (tossed with a little oil and salt) on the other; roast 16–18 minutes until the chicken hits 165°F and the beans blister.",
      "Rest the chicken 5 minutes so it stays juicy when boxed, then divide rice, beans and chicken across four containers.",
      "Spoon the tray juices over each box before lidding — that's the dressing.",
    ],
    tip: "Boxes keep 4 days chilled. Reheat lidded with a teaspoon of water so the rice steams back; a fresh lemon wedge in each box on day three revives everything.",
  },
];

// Authored first so the catalog's existing order never shifts.
export const SHAPE_KITCHEN_RECIPES = [..._SHAPE_KITCHEN_RECIPES_AUTHORED, ...USDA_KITCHEN_RECIPES];

// ── PR D orchestration (§6): passive-window overlay ────────────────────────
// Marks ONLY the genuinely hands-off windows in the catalog — a real duration
// plus a station you can walk away from — so a Prep Session can interleave
// ("while the chicken roasts, start tomorrow's rice"). Every other step stays
// active and the board never fabricates parallelism. Steps themselves stay plain
// strings (no consumer changes); this attaches a parallel `stepMeta` array.
// Hand-checked against each step's text; the data test ties every `min` to that
// step's own stated duration (bsStepTimers) so authored metadata can't drift.
//   station: 'oven' | 'stove' | 'board' | 'off'   ('off' = rest/chill/marinate —
//   ties up no equipment, so it never conflicts). Keyed title → { stepIndex: meta }.
// An annotation declares "this recipe's NEXT step waits for the hold" — the
// board's wait gate blocks same-recipe continuation while the window runs. So a
// window whose next step is authored CONCURRENT with it ("While it roasts, make
// the couscous…" / "Meanwhile…") must NOT be annotated (Codex, PR D round 5) —
// the gate would contradict the recipe's own text and lock the cook out of work
// the author scheduled inside the window. Intra-recipe overlap is PR E
// structured-authoring territory. Guarded by tests/shape-kitchen-data.test.mjs.
// ---------------------------------------------------------------------------
// Attribution — the ONE place that decides how a recipe is credited.
//
// There are two honest ways to be credited and they are not interchangeable. An
// authored recipe carries by + byRole and reads "from the kitchen of <person>".
// A public-domain federal work (USDA MyPlate Kitchen, 17 USC § 105) has no
// author at all; crediting it to a nutritionist would be a fabricated byline, so
// it carries source + sourceUrl + license and is credited to the SOURCE.
//
// ⚠ Every surface must go through this. Before it existed, three render sites
// called `.by.toUpperCase()` directly, which throws on a sourced recipe and took
// the whole page down; a fourth interpolated `${r.byRole} · ${r.by}` and printed
// "null · null". Returning null for an uncredited recipe is deliberate: the
// caller renders NOTHING rather than inventing a name.
export const bsRecipeAttribution = (r) => {
  if (!r || typeof r !== 'object') return null;
  const nonEmpty = (v) => (typeof v === 'string' && v.trim() ? v.trim() : null);
  const by = nonEmpty(r.by);
  if (by) return { kind: 'authored', name: by, role: nonEmpty(r.byRole), url: null };
  const source = nonEmpty(r.source);
  if (source) return { kind: 'sourced', name: source, role: null, url: nonEmpty(r.sourceUrl) };
  return null;
};

export const _KITCHEN_STEP_META = {
  "One-pan chicken and rice": { 4: { min: 18, passive: true, station: "stove" } },
  "Sheet-pan salmon, sweet potato and broccoli": { 4: { min: 12, passive: true, station: "oven" } },
  "Steak and sweet potato hash": { 1: { min: 8, passive: true, station: "stove" }, 4: { min: 4, passive: true, station: "off" } },
  "Red lentil and spinach dahl": { 4: { min: 18, passive: true, station: "stove" } },
  "Chickpea shakshuka": { 2: { min: 8, passive: true, station: "stove" }, 4: { min: 5, passive: true, station: "stove" } },
  "Tofu and edamame poke bowl": { 0: { min: 10, passive: true, station: "off" } },
  "Grilled chicken Caesar, lightened": { 2: { min: 5, passive: true, station: "off" } },
  "Beef and broccoli stir-fry": { 0: { min: 10, passive: true, station: "off" } },
  "Tempeh and broccoli teriyaki": { 0: { min: 5, passive: true, station: "stove" } },
  "Tuna niçoise bowl": { 0: { min: 7, passive: true, station: "stove" } },
  "Roasted veg and halloumi traybake": { 2: { min: 20, passive: true, station: "oven" }, 3: { min: 10, passive: true, station: "oven" } },
  "Black-eyed pea and coconut curry": { 3: { min: 15, passive: true, station: "stove" } },
  "Cauliflower steak, chimichurri": { 4: { min: 10, passive: true, station: "off" } },
  "Creamy tomato and white bean pasta": { 1: { min: 8, passive: true, station: "stove" } },
  "Beef ragu rigatoni": { 3: { min: 20, passive: true, station: "stove" } },
  "Chickpea and spinach curry": { 4: { min: 15, passive: true, station: "stove" } },
  "Crispy tofu grain bowl": { 0: { min: 10, passive: true, station: "off" } },
  "Overnight oats, three ways": { 1: { min: 240, passive: true, station: "off" } },
  "Harissa salmon with couscous": { 2: { min: 5, passive: true, station: "off" } },
  "Date and almond energy bites": { 3: { min: 30, passive: true, station: "off" } },
  "Turkey chili verde": { 4: { min: 20, passive: true, station: "stove" } },
  "Lemon-herb chicken meal-prep box": { 0: { min: 10, passive: true, station: "off" }, 1: { min: 15, passive: true, station: "stove" }, 2: { min: 16, passive: true, station: "oven" } },
};
for (const r of SHAPE_KITCHEN_RECIPES) {
  const m = _KITCHEN_STEP_META[r.title];
  if (m) r.stepMeta = r.steps.map((_, i) => m[i] || null);
}

// Dietary-needs axis (multi-match) layered on top of the single `diet`. Keep in
// sync with public/newdesign/recipes.jsx.
export const RECIPE_DIETS = ["Vegan", "Vegetarian", "Pescatarian", "Mediterranean"];
export const RECIPE_PROTEINS = ["Seafood", "Poultry", "Meat"];
export const RECIPE_FREE_FROM = ["Gluten-free", "Dairy-free"];
export const RECIPE_GOALS = ["High-protein", "Low-carb"];
export const _RECIPE_NOT_GF = new Set([
  "Tempo turkey lettuce cups", "Miso-glazed cod with greens", "Tofu and edamame poke bowl",
  "Grilled chicken Caesar, lightened", "Beef and broccoli stir-fry", "Tempeh and broccoli teriyaki",
  "Turkey meatballs in marinara", "Smoked salmon and avocado toast", "Greek yogurt power bowl",
  "Chicken pesto pasta", "Garlic shrimp linguine", "Lentil bolognese", "Creamy tomato and white bean pasta", "Beef ragu rigatoni",
  "Crispy tofu grain bowl", "Overnight oats, three ways", "Harissa salmon with couscous", "Cottage cheese protein toast",
  // ⚠ PRE-EXISTING, not introduced by the USDA merge: rolled oats, same rule as
  // "Overnight oats" two entries up, which was already classified correctly.
  "Date and almond energy bites",
  ...USDA_NOT_GF,
]);
export const _RECIPE_HAS_DAIRY = new Set([
  "Greek yogurt power bowl", "Shrimp and quinoa harvest bowl", "Chickpea shakshuka",
  "Grilled chicken Caesar, lightened", "Roasted veg and halloumi traybake", "Turkey meatballs in marinara",
  "Chicken pesto pasta", "Creamy tomato and white bean pasta", "Beef ragu rigatoni",
  "Overnight oats, three ways", "Garlic shrimp and courgette noodles", "Cottage cheese protein toast",
  ...USDA_HAS_DAIRY,
]);
export const _RECIPE_MED = new Set([
  "Sheet-pan salmon, sweet potato and broccoli", "Shrimp and quinoa harvest bowl", "Chickpea shakshuka",
  "Tuna niçoise bowl", "Roasted veg and halloumi traybake",
  "Harissa salmon with couscous", "Lemon-herb chicken meal-prep box",
  ...USDA_MED,
]);
export function recipeNeeds(r) {
  const out = [];
  const p = (r.macros && r.macros.p) || 0;
  const c = (r.macros && r.macros.c) || 0;
  if (p >= 30) out.push("High-protein");
  if (c <= 40) out.push("Low-carb");
  if (!_RECIPE_NOT_GF.has(r.title)) out.push("Gluten-free");
  if (!_RECIPE_HAS_DAIRY.has(r.title)) out.push("Dairy-free");
  return out;
}
export function recipeMatchesDiet(r, diet) {
  if (!diet || diet === "All") return true;
  if (diet === "Pescatarian") return r.diet !== "Meat" && r.diet !== "Poultry";
  if (diet === "Mediterranean") return _RECIPE_MED.has(r.title);
  return r.diet === diet;
}
